### ISSUE TITLE
CPP Project Templates not found on Windows 7

### ISSUE THREAD

**Issue by appelgriebsch** [felixrieseberg/windows-build-tools#10]
Trying to install & build the LevelDB adapter on recent node.js results in:

...\leveldown\deps\leveldb\leveldb.vcxproj(20,3): error MSB4019: The imported project "S:\Microsoft.Cpp.Default.props" was not found. Confirm that the path in the <Import> declaration is correct, and that the file exists on disk.

**Comment by A92hm** [comment]
@appelgriebsch Thank you for reporting this issue. I'm currently installing Windows 7 on a VM to test this; however, I got the same error on a clean install of Windows 10 as well (after running `npm install windows-build-tools` of course).

I will investigate this issue and make a PR to solve it.

**Comment by A92hm** [comment]
It seems like this issue is solved as I tested it on both Windows 7 and 10 with node v6.9.0 LTS.
Can you confirm this works for you?

**Comment by appelgriebsch** [comment]
Sorry, I've had to install Visual Studio recently. So I'm currently unable to test it...

**Comment by appelgriebsch** [comment]
Just tried it on another machine not having Visual Studio 2015 installed already. Installing a Node.js project that has leveldown / leveldb as dependency results in leveldb being build successfully now. Thx.

**Comment by orangemi** [comment]
I still met the problem in Windows 10. One machine with Visual Studio 2015 and one without any Visual Studio. 
```
PS C:\Users\teambition\projects\printer-demo2> node --version
v7.7.2
PS C:\Users\teambition\projects\printer-demo2> npm --version
4.1.2
PS C:\Users\teambition\projects\printer-demo2> npm i --save printer

> printer@0.2.2 install C:\Users\teambition\projects\printer-demo2\node_modules\printer
> node-gyp rebuild


C:\Users\teambition\projects\printer-demo2\node_modules\printer>if not defined npm_config_node_gyp (node "C:\Program Files\nodejs\node_modules\npm\bin\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild )  else (node "" rebuild )
在此解决方案中一次生成一个项目。若要启用并行生成，请添加“/m”开关。
C:\Users\teambition\projects\printer-demo2\node_modules\printer\build\node_printer.vcxproj(20,3): error MSB4019: 未找到导入的项目“C:\Program Files (x86)\MSBuild\Microsoft.Cpp\v4.0\V110\Microsoft.Cpp.Default.props”。请确认 <Import> 声明中的路径正确，且磁盘上存在该文件。
gyp ERR! build error
gyp ERR! stack Error: `msbuild` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onExit (C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\build.js:276:23)
gyp ERR! stack     at emitTwo (events.js:106:13)
gyp ERR! stack     at ChildProcess.emit (events.js:194:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:215:12)
gyp ERR! System Windows_NT 10.0.14393
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd C:\Users\teambition\projects\printer-demo2\node_modules\printer
gyp ERR! node -v v7.7.2
gyp ERR! node-gyp -v v3.5.0
gyp ERR! not ok
npm WARN printer-demo2@1.0.0 No description
npm WARN printer-demo2@1.0.0 No repository field.
npm ERR! Windows_NT 10.0.14393
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "i" "--save" "printer"
npm ERR! node v7.7.2
npm ERR! npm  v4.1.2
npm ERR! code ELIFECYCLE

npm ERR! printer@0.2.2 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the printer@0.2.2 install script 'node-gyp rebuild'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the printer package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs printer
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls printer
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Users\teambition\projects\printer-demo2\npm-debug.log
```
