### ISSUE TITLE
Downloading BuildTools_Full.exe (Error: tunneling socket could not be established, statusCode=500)

### ISSUE THREAD

**Issue by syrahmae** [felixrieseberg/windows-build-tools#102]
$ npm install --global --production windows-build-tools

> windows-build-tools@2.2.1 postinstall C:\Users\User\AppData\Roaming\npm\node_modules\windows-build-tools
> node ./lib/index.js

> Downloading BuildTools_Full.exe
Error: tunneling socket could not be established, statusCode=500
{ Error: tunneling socket could not be established, statusCode=500
    at ClientRequest.onConnect (C:\Users\User\AppData\Roaming\npm\node_modules\windows-build-tools\node_modules\tunnel-agent\index.js:166:19)
    at Object.onceWrapper (events.js:319:30)
    at emitThree (events.js:136:13)
    at ClientRequest.emit (events.js:217:7)
    at Socket.socketOnData (_http_client.js:472:11)
    at emitOne (events.js:116:13)
    at Socket.emit (events.js:211:7)
    at addChunk (_stream_readable.js:263:12)
    at readableAddChunk (_stream_readable.js:250:11)
    at Socket.Readable.push (_stream_readable.js:208:10) code: 'ECONNRESET' } windows-build-tools@2.2.1
updated 1 package in 16.641s`

**Comment by jacobq** [comment]
It looks like there is a connection problem (got HTTP 500 response?) Could you confirm that you are able to download this file when directly using the URLs?
https://download.visualstudio.microsoft.com/download/pr/11503713/e64d79b40219aea618ce2fe10ebd5f0d/vs_BuildTools.exe
https://download.microsoft.com/download/5/f/7/5f7acaeb-8363-451f-9425-68a90f98b238/visualcppbuildtools_full.exe
They both seem to work for me.

**Comment by celolima** [comment]
Unfortunately the second option
 [https://download.microsoft.com/download/5/f/7/5f7acaeb-8363-451f-9425-68a90f98b238/visualcppbuildtools_full.exe](url) 
is not working anymore.

**Comment by jacobq** [comment]
@celolima It works from my location. (MD5 sum `8d4afd3b226babecaa4effb10d69eb2e` for `visualcppbuildtools_full.exe`)

**Comment by felixrieseberg** [comment]
I've double-checked this using a few different locations and we _should_ be fine.
