### ISSUE TITLE
 Error: EBUSY: resource busy or locked

### ISSUE THREAD

**Issue by 36ban** [felixrieseberg/windows-build-tools#118]
👍 win10  node10.3.0  npm6.1, Windows Powershell(admin)
I deleted npm and npm-cache before I installed this
```
PS F:\workspace\client> npm install --global --production windows-build-tools

> windows-build-tools@2.3.0 postinstall C:\Users\Think\AppData\Roaming\npm\node_modules\windows-build-tools
> node ./lib/index.js

Downloading python-2.7.14.amd64.msi
Downloading BuildTools_Full.exe
[>                                            ] 0.0% (0 B/s)
Downloaded BuildTools_Full.exe. Saved to C:\Users\Think\.windows-build-tools\BuildTools_Full.exe.

Starting installation...
{ Error: EBUSY: resource busy or locked, unlink 'C:\Users\Think\.windows-build-tools\build-tools-log.txt'
    at Object.fs.unlinkSync (fs.js:1047:3)
    at C:\Users\Think\AppData\Roaming\npm\node_modules\windows-build-tools\lib\utils\clean.js:21:10
    at Array.forEach (<anonymous>)
    at cleanExistingLogFiles (C:\Users\Think\AppData\Roaming\npm\node_modules\windows-build-tools\lib\utils\clean.js:19:9)
    at install (C:\Users\Think\AppData\Roaming\npm\node_modules\windows-build-tools\lib\install\index.js:49:3)
    at C:\Users\Think\AppData\Roaming\npm\node_modules\windows-build-tools\lib\index.js:18:3
    at C:\Users\Think\AppData\Roaming\npm\node_modules\windows-build-tools\lib\download.js:17:12
    at process._tickCallback (internal/process/next_tick.js:68:7)
  errno: -4082,
  syscall: 'unlink',
  code: 'EBUSY',
  path:
   'C:\\Users\\Think\\.windows-build-tools\\build-tools-log.txt' }
+ windows-build-tools@2.3.0
added 140 packages from 91 contributors in 12.579s
```

**Comment by 36ban** [comment]
https://stackoverflow.com/questions/29853255/ebusy-resource-busy-or-locked-open-path-here

**Comment by Aakashbio** [comment]
run command cordova clean
