### ISSUE TITLE
'ml' is not recognized as an internal or external command

### ISSUE THREAD

**Issue by ryanvgates** [felixrieseberg/windows-build-tools#122]
I get an error stating

<pre>  'ml' is not recognized as an internal or external command,
  operable program or batch file.
C:\Users\RyanGat\Source\Repos\windows-build-tools-issue\node_modules\ffi-napi\build\deps\libffi\ffi.targets(28,5): error MSB3721: The command "call ml "/nologo" "/safeseh" "/c" "/FoRelease\obj\ffi\win32.obj" "..\..\..\deps\libffi\src\x8
6\win32.asm"" exited with code 1. [C:\Users\RyanGat\Source\Repos\windows-build-tools-issue\node_modules\ffi-napi\build\deps\libffi\ffi.vcxproj]</pre>

I had entered [a separate issue](https://github.com/ukoloff/win-ca/issues/2) in the win-ca repository. However it seems to center around the windows-build-tools and the having VS installed at `C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\bin` rather than `C:\Program Files\Microsoft Visual Studio 14.0\VC\bin`

**To Reproduce:**

1. Create an empty folder 
1. Run `npm init -y`
2. Run `npm install --global windows-build-tools` and below is my output
<pre>user@machine MINGW64 /c/Users/user/Source/Repos/windows-build-tools-issue
$ npm install --global windows-build-tools

> windows-build-tools@3.0.0 postinstall C:\Users\user\AppData\Roaming\npm\node_modules\windows-build-tools
> node ./dist/index.js

Downloading BuildTools_Full.exe
[>                                            ] 0.0% (0 B/s)
Downloaded BuildTools_Full.exe. Saved to C:\Users\user\.windows-build-tools\BuildTools_Full.exe.

Starting installation...
Launched installers, now waiting for them to finish.
This will likely take some time - please be patient!

Status from the installers:
---------- Visual Studio Build Tools ----------
Successfully installed Visual Studio Build Tools.
------------------- Python --------------------
Python 2.7.14 is already installed, not installing again.

All done!

+ windows-build-tools@3.0.0
added 1 package from 1 contributor and updated 2 packages in 71.689s</pre>

3. Run `npm i --save win-ca`
<pre>
RyanGat-CA@L04283RYANGAT MINGW64 /c/Users/RyanGat/Source/Repos/windows-build-tools-issue
$ npm i --save win-ca

> ref-napi@1.4.0 install C:\Users\RyanGat\Source\Repos\windows-build-tools-issue\node_modules\ref-napi
> node-gyp rebuild

C:\Users\RyanGat\Source\Repos\windows-build-tools-issue\node_modules\ref-napi>if not defined npm_config_node_gyp (node "C:\Users\RyanGat-CA\AppData\Roaming\npm\node_modules\npm\node_modules\npm-lifecycle\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild )  else (node "C:\Users\RyanGat-CA\AppData\Roaming\npm\node_modules\npm\node_modules\node-gyp\bin\node-gyp.js" rebuild )
Building the projects in this solution one at a time. To enable parallel build, please add the "/m" switch.
  win_delay_load_hook.cc
  Generating code
  Finished generating code
  nothing.vcxproj -> C:\Users\RyanGat\Source\Repos\windows-build-tools-issue\node_modules\ref-napi\build\Release\\nothing.node
  nothing.vcxproj -> C:\Users\RyanGat\Source\Repos\windows-build-tools-issue\node_modules\ref-napi\build\Release\nothing.pdb (Full PDB)
  binding.cc
  win_delay_load_hook.cc
..\src\binding.cc(177): warning C4244: 'argument': conversion from 'int64_t' to 'std::size_t', possible loss of data [C:\Users\RyanGat\Source\Repos\windows-build-tools-issue\node_modules\ref-napi\build\binding.vcxproj]
..\src\binding.cc(229): warning C4244: 'argument': conversion from 'int64_t' to 'double', possible loss of data [C:\Users\RyanGat\Source\Repos\windows-build-tools-issue\node_modules\ref-napi\build\binding.vcxproj]
..\src\binding.cc(298): warning C4244: 'argument': conversion from 'uint64_t' to 'double', possible loss of data [C:\Users\RyanGat\Source\Repos\windows-build-tools-issue\node_modules\ref-napi\build\binding.vcxproj]
..\src\binding.cc(384): warning C4244: 'argument': conversion from 'int64_t' to 'std::size_t', possible loss of data [C:\Users\RyanGat\Source\Repos\windows-build-tools-issue\node_modules\ref-napi\build\binding.vcxproj]
     Creating library C:\Users\RyanGat\Source\Repos\windows-build-tools-issue\node_modules\ref-napi\build\Release\binding.lib and object C:\Users\RyanGat\Source\Repos\windows-build-tools-issue\node_modules\ref-napi\build\Release\binding
  .exp
  Generating code
  Finished generating code
  binding.vcxproj -> C:\Users\RyanGat\Source\Repos\windows-build-tools-issue\node_modules\ref-napi\build\Release\\binding.node
  binding.vcxproj -> C:\Users\RyanGat\Source\Repos\windows-build-tools-issue\node_modules\ref-napi\build\Release\binding.pdb (Full PDB)

> ffi-napi@2.4.3 install C:\Users\RyanGat\Source\Repos\windows-build-tools-issue\node_modules\ffi-napi
> node-gyp rebuild

C:\Users\RyanGat\Source\Repos\windows-build-tools-issue\node_modules\ffi-napi>if not defined npm_config_node_gyp (node "C:\Users\RyanGat-CA\AppData\Roaming\npm\node_modules\npm\node_modules\npm-lifecycle\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild )  else (node "C:\Users\RyanGat-CA\AppData\Roaming\npm\node_modules\npm\node_modules\node-gyp\bin\node-gyp.js" rebuild )
Building the projects in this solution one at a time. To enable parallel build, please add the "/m" switch.
  Building assembly file ..\..\..\deps\libffi\src\x86\win32.asm
  'ml' is not recognized as an internal or external command,
  operable program or batch file.
C:\Users\RyanGat\Source\Repos\windows-build-tools-issue\node_modules\ffi-napi\build\deps\libffi\ffi.targets(28,5): error MSB3721: The command "call ml "/nologo" "/safeseh" "/c" "/FoRelease\obj\ffi\win32.obj" "..\..\..\deps\libffi\src\x8
6\win32.asm"" exited with code 1. [C:\Users\RyanGat\Source\Repos\windows-build-tools-issue\node_modules\ffi-napi\build\deps\libffi\ffi.vcxproj]
  win_delay_load_hook.cc
  Generating code
  Finished generating code
  nothing.vcxproj -> C:\Users\RyanGat\Source\Repos\windows-build-tools-issue\node_modules\ffi-napi\build\Release\\nothing.node
  nothing.vcxproj -> C:\Users\RyanGat\Source\Repos\windows-build-tools-issue\node_modules\ffi-napi\build\Release\nothing.pdb (Full PDB)
gyp ERR! build error
gyp ERR! stack Error: `C:\Program Files (x86)\MSBuild\14.0\bin\msbuild.exe` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onExit (C:\Users\RyanGat-CA\AppData\Roaming\npm\node_modules\npm\node_modules\node-gyp\lib\build.js:258:23)
gyp ERR! stack     at emitTwo (events.js:126:13)
gyp ERR! stack     at ChildProcess.emit (events.js:214:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:198:12)
gyp ERR! System Windows_NT 10.0.15063
gyp ERR! command "C:\\Program Files (x86)\\nodejs\\node.exe" "C:\\Users\\RyanGat-CA\\AppData\\Roaming\\npm\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd C:\Users\RyanGat\Source\Repos\windows-build-tools-issue\node_modules\ffi-napi
gyp ERR! node -v v8.11.2
gyp ERR! node-gyp -v v3.6.2
gyp ERR! not ok
npm notice created a lockfile as package-lock.json. You should commit this file.
npm WARN windows-build-tools-issue@1.0.0 No description
npm WARN windows-build-tools-issue@1.0.0 No repository field.
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: ffi-napi@2.4.3 (node_modules\ffi-napi):
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: ffi-napi@2.4.3 install: `node-gyp rebuild`
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: Exit status 1

+ win-ca@1.1.0
added 2 packages from 5 contributors in 41.281s
</pre>

Please let me know if you need any additional information.

**Comment by ryanvgates** [comment]
I resolved this issue by adding `C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\bin` to my PATH. That resolved the issue.
