### ISSUE TITLE
Installation issue with node 6.9.1 and windows-build-tools 4.0.0

### ISSUE THREAD

**Issue by kuffis** [felixrieseberg/windows-build-tools#140]
The simplest possible installation with
npm i -g windows-build-tools
fails with node 6.9.1. 

The second-simplest installation with npm i -g windows-build-tools@3.1.0 works.

```
C:\WINDOWS\system32>npm i -g windows-build-tools
npm WARN deprecated debug@3.2.4: `debug` versions 3.2.0-3.2.2 break Node 4. User
s of node LTS and onward (modern Node versions): please upgrade to `debug@4` or
above as soon as possible. Node 4 users: please pin to `debug@>=3.2.3 <4` as it
will be the last version range that supports Node@4.

> windows-build-tools@4.0.0 postinstall C:\Users\C948066\AppData\Roaming\npm\nod
e_modules\windows-build-tools
> node ./dist/index.js

C:\Users\C948066\AppData\Roaming\npm\node_modules\windows-build-tools\dist\aquir
e-installers.js:15
async function aquireInstallers(cb) {
      ^^^^^^^^
SyntaxError: Unexpected token function
    at Object.exports.runInThisContext (vm.js:76:16)
    at Module._compile (module.js:542:28)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (C:\Users\C948066\AppData\Roaming\npm\node_modules\win
dows-build-tools\dist\start.js:4:29)
    at Module._compile (module.js:570:32)
npm ERR! Windows_NT 6.1.7601
npm ERR! argv "C:\\apps\\nodejs\\node.exe" "C:\\Users\\C948066\\AppData\\Roaming
\\npm\\node_modules\\npm\\bin\\npm-cli.js" "i" "-g" "windows-build-tools"
npm ERR! node v6.9.1
npm ERR! npm  v3.10.8
npm ERR! code ELIFECYCLE

npm ERR! windows-build-tools@4.0.0 postinstall: `node ./dist/index.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the windows-build-tools@4.0.0 postinstall script 'node ./dist
/index.js'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the windows-build-tools p
ackage,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node ./dist/index.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs windows-build-tools
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls windows-build-tools
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     C:\WINDOWS\system32\npm-debug.log

C:\WINDOWS\system32>node --version
v6.9.1

```

**Comment by felixrieseberg** [comment]
From the release notes:

> ⚠️ Breaking change: windows-build-tools now requires Node v8. Use windows-build-tools@3.1.0 if you're running Node v6.

**Comment by robelkebede44** [comment]
what if i want to use v6

**Comment by jacobq** [comment]
@robelkebede44 If you are OK with using an old version of node why not also use an old version of `windows-build-tools`? Just don't upgrade to 4.x, e.g. `npm install --global --production windows-build-tools@3`. However, I would strongly advise you to upgrade from node 6.x as soon as possible because it is unsupported not only by this module but by the Node Foundation itself, which means it no longer receives security patches, etc.
