### ISSUE TITLE
Error on Windows XP

### ISSUE THREAD

**Issue by lishichao1002** [felixrieseberg/windows-build-tools#142]
```
{ soda-b-pc } nsis » npm install --global --production windows-build-tools                                                                                                                       /cygdrive/y/workspaces/webstorm/soda-b-pc
npm WARN engine windows-build-tools@4.0.0: wanted: {"node":">=8.0.0"} (current: {"node":"5.2.0","npm":"3.3.12"})
npm WARN engine windows-build-tools@4.0.0: wanted: {"node":">=8.0.0"} (current: {"node":"5.2.0","npm":"3.3.12"})
npm WARN engine fs-extra@7.0.0: wanted: {"node":">=6 <7 || >=8"} (current: {"node":"5.2.0","npm":"3.3.12"})

> windows-build-tools@4.0.0 postinstall C:\Documents and Settings\Administrator\Application Data\npm\node_modules\windows-build-tools
> node ./dist/index.js

C:\Documents and Settings\Administrator\Application Data\npm\node_modules\windows-build-tools\dist\compatible.js:4
        const { warn } = require('./logging');
              ^

SyntaxError: Unexpected token {
    at exports.runInThisContext (vm.js:54:16)
    at Module._compile (module.js:375:25)
    at Object.Module._extensions..js (module.js:406:10)
    at Module.load (module.js:345:32)
    at Function.Module._load (module.js:302:12)
    at Module.require (module.js:355:17)
    at require (internal/module.js:13:17)
    at Object.<anonymous> (C:\Documents and Settings\Administrator\Application Data\npm\node_modules\windows-build-tools\dist\index.js:6:1)
    at Module._compile (module.js:399:26)
    at Object.Module._extensions..js (module.js:406:10)
npm ERR! Windows_NT 5.1.2600
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "--global" "--production" "windows-build-tools"
npm ERR! node v5.2.0
npm ERR! npm  v3.3.12
npm ERR! code ELIFECYCLE

npm ERR! windows-build-tools@4.0.0 postinstall: `node ./dist/index.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the windows-build-tools@4.0.0 postinstall script 'node ./dist/index.js'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the windows-build-tools package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node ./dist/index.js
npm ERR! You can get their info via:
npm ERR!     npm owner ls windows-build-tools
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     Y:\workspaces\webstorm\soda-b-pc\npm-debug.log
```

**Comment by felixrieseberg** [comment]
You're running an unsupported version of Node. Please see the README for details!

**Comment by marcorivm** [comment]
I'm sorry to come back and open this issue, but currently facing the same issue, trying to install on a XP machine, I have node 5.12 runnig, is this possible?

**Comment by jacobq** [comment]
@marcorivm No, you'd have to use an older version of `windows-build-tools` in order to be compatible with old versions of node. See [releases](https://github.com/felixrieseberg/windows-build-tools/releases): v4.x requires Node 8.x. You could try your luck with `npm install -g windows-build-tools@3.1.0` or `2.3.0`, but there's no guarantee that it'll work, especially considering that the URLs for downloading the installers may change, and it is also possible that the Python installer or MS build tools installer will not work on Windows XP.

If at all possible, you should upgrade your OS to something supported by the current version of Node and then start working toward upgrading to a maintained version of Node. If that's not an option, you can manually download & run the installers that this package fetches (after all, it's just for convenience), but you're going to be fighting an uphill battle and having to deal with serious security vulnerabilities on your own.

**Comment by marcorivm** [comment]
Thank you for taking the time to answer @jacobq 

I think for the size of the program I'm running it would be easier to port it to another language, probably .net that is supported on the machine. I don't have many options to change that computers software unfortunately.
