### ISSUE TITLE
Unable to install `windows-build-tools`, due to problem in `dist/aquire-installers.js`

### ISSUE THREAD

**Issue by ericnewton76** [felixrieseberg/windows-build-tools#153]
Unable to install `windows-build-tools`, due to problem in `dist/aquire-installers.js` (acquire spelled incorrectly btw)

```
C:\Users\eric>npm install --global --production windows-build-tools

> windows-build-tools@5.0.0 postinstall C:\Users\Eric\AppData\Local\npm\node_modules\windows-build-tools
> node ./dist/index.js

C:\Users\Eric\AppData\Local\npm\node_modules\windows-build-tools\dist\aquire-installers.js:15
async function aquireInstallers(cb) {
      ^^^^^^^^

SyntaxError: Unexpected token function
    at createScript (vm.js:56:10)
    at Object.runInThisContext (vm.js:97:10)
    at Module._compile (module.js:542:28)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (C:\Users\Eric\AppData\Local\npm\node_modules\windows-build-tools\dist\start.js:4:29)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! windows-build-tools@5.0.0 postinstall: `node ./dist/index.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the windows-build-tools@5.0.0 postinstall script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Eric\AppData\Roaming\npm-cache\_logs\2018-10-24T17_01_58_913Z-debug.log
```

Version info:
```
C:\>node --version
v6.11.3

C:\>npm --version
6.4.1
```

**Comment by ericnewton76** [comment]
Hmmm, maybe node is too old? (Thought I had v8) 

Your package.json should include a req of `node >= 8` possibly

**Comment by ericnewton76** [comment]
Uh, hmmm.

Looks like you have engines >= 8

https://github.com/felixrieseberg/windows-build-tools/blob/master/package.json#L30

Bizarre!!!

**Comment by ericnewton76** [comment]
Closing this.  NPM didn't do anything to warn me that windows-build-tools at 4 and 5 require node v8.

Very odd.  

Fixed by installing node v8
