### ISSUE TITLE
403 Forbidden: speedometer@~0.1.2

### ISSUE THREAD

**Issue by sagardevangare** [felixrieseberg/windows-build-tools#160]
not able to install in windows system 
>npm install --global windows-build-tools --verbos

O/P
```
npm http fetch GET 200 https://registry.npmjs.org/is-finite 2ms (from cache)
npm http fetch GET 200 https://registry.npmjs.org/number-is-nan 4ms (from cache)
npm http fetch GET 200 https://registry.npmjs.org/through2 18ms (from cache)
npm http fetch GET 403 https://registry.npmjs.org/speedometer 613ms
npm timing stage:rollbackFailedOptional Completed in 6ms
npm timing stage:runTopLevelLifecycles Completed in 1280ms
npm verb stack Error: 403 Forbidden: speedometer@~0.1.2
npm verb stack     at fetch.then.res (C:\Program Files\nodejs\node_modules\npm\node_modules\pacote\lib\fetchers\registry\fetch.js:42:19)
npm verb stack     at tryCatcher (C:\Program Files\nodejs\node_modules\npm\node_modules\bluebird\js\release\util.js:16:23)
npm verb stack     at Promise._settlePromiseFromHandler (C:\Program Files\nodejs\node_modules\npm\node_modules\bluebird\js\release\promise.js:512:31)
npm verb stack     at Promise._settlePromise (C:\Program Files\nodejs\node_modules\npm\node_modules\bluebird\js\release\promise.js:569:18)
npm verb stack     at Promise._settlePromise0 (C:\Program Files\nodejs\node_modules\npm\node_modules\bluebird\js\release\promise.js:614:10)
npm verb stack     at Promise._settlePromises (C:\Program Files\nodejs\node_modules\npm\node_modules\bluebird\js\release\promise.js:693:18)
npm verb stack     at Async._drainQueue (C:\Program Files\nodejs\node_modules\npm\node_modules\bluebird\js\release\async.js:133:16)
npm verb stack     at Async._drainQueues (C:\Program Files\nodejs\node_modules\npm\node_modules\bluebird\js\release\async.js:143:10)
npm verb stack     at Immediate.Async.drainQueues [as _onImmediate] (C:\Program Files\nodejs\node_modules\npm\node_modules\bluebird\js\release\async.js:17:14)
npm verb stack     at runCallback (timers.js:705:18)
npm verb stack     at tryOnImmediate (timers.js:676:5)
npm verb stack     at processImmediate (timers.js:658:5)
npm verb cwd D:\Project\RTI\rti-campus-app-frontend
npm verb Windows_NT 10.0.10586
npm verb argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "--global" "windows-build-tools" "--verbos"
npm verb node v10.13.0
npm verb npm  v6.4.1
npm ERR! code E403
npm ERR! 403 Forbidden: speedometer@~0.1.2
npm verb exit [ 1, true ]
npm timing npm Completed in 1731ms

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\1000849\AppData\Roaming\npm-cache\_logs\2018-11-14T11_43_46_100Z-debug.log
```

**Comment by jacobq** [comment]
That looks a lot like a network (filtering / connectivity) or npm problem. What version of node are you using and what happens when you attempt to install other packages?

**Comment by felixrieseberg** [comment]
I agree, this is like ya network fluke.
