### ISSUE TITLE
installation fails at postinstall

### ISSUE THREAD

**Issue by hansifer** [felixrieseberg/windows-build-tools#161]
> npm install --global windows-build-tools
```
> windows-build-tools@5.0.0 postinstall node_modules\windows-build-tools
> node ./dist/index.js

npm ERR! file bash
npm ERR! path bash
npm ERR! code ELIFECYCLE
npm ERR! errno ENOENT
npm ERR! syscall spawn bash
npm ERR! windows-build-tools@5.0.0 postinstall: `node ./dist/index.js`
npm ERR! spawn bash ENOENT
npm ERR!
npm ERR! Failed at the windows-build-tools@5.0.0 postinstall script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
```
```
> node -v
v8.12.0
> npm -v
6.4.1
```
Windows 10
Tried with Git Bash, cmd, and PowerShell *as administrator*

Additional logging:
```
4076 info lifecycle windows-build-tools@5.0.0~postinstall: windows-build-tools@5.0.0
4077 verbose lifecycle windows-build-tools@5.0.0~postinstall: unsafe-perm in lifecycle true
4080 silly lifecycle windows-build-tools@5.0.0~postinstall: Args: [ '-c', 'node ./dist/index.js' ]
4081 info lifecycle windows-build-tools@5.0.0~postinstall: Failed to exec postinstall script
4082 silly lifecycle windows-build-tools@5.0.0~postinstall: Returned: code: -4058  signal: null
4088 verbose stack Error: windows-build-tools@5.0.0 postinstall: `node ./dist/index.js`
4088 verbose stack spawn bash ENOENT
4088 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:190:19)
4088 verbose stack     at onErrorNT (internal/child_process.js:362:16)
4088 verbose stack     at _combinedTickCallback (internal/process/next_tick.js:139:11)
4088 verbose stack     at process._tickCallback (internal/process/next_tick.js:181:9)
4089 verbose pkgid windows-build-tools@5.0.0
4091 verbose Windows_NT 10.0.17134
4093 verbose node v8.12.0
4094 verbose npm  v6.4.1
```

**Comment by blowsie** [comment]
I also have this issue
