### ISSUE TITLE
SyntaxError: Unexpected token

### ISSUE THREAD

**Issue by Megachip** [felixrieseberg/windows-build-tools#165]
´´´´
> windows-build-tools@5.0.0 postinstall F:\PortableApps\NodeJSPortable\App\node_modules\windows-build-tools
> node ./dist/index.js

F:\PortableApps\NodeJSPortable\App\node_modules\windows-build-tools\dist\compatible.js:4
        const { warn } = require('./logging');
              ^

SyntaxError: Unexpected token {
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:387:25)
    at Object.Module._extensions..js (module.js:422:10)
    at Module.load (module.js:357:32)
    at Function.Module._load (module.js:314:12)
    at Module.require (module.js:367:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (F:\PortableApps\NodeJSPortable\App\node_modules\windows-build-tools\dist\index.js:6:1)
    at Module._compile (module.js:413:34)
    at Object.Module._extensions..js (module.js:422:10)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! windows-build-tools@5.0.0 postinstall: `node ./dist/index.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the windows-build-tools@5.0.0 postinstall script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\megac\AppData\Roaming\npm-cache\_logs\2018-12-23T10_02_55_351Z-debug.log
´´´´

**Comment by refack** [comment]
Hello @Megachip,
I see you are using node@5.12.0. It's a very old version, and it's not supported by the Node.js org, and AFAICT nor by [`windows-build-tools`](https://github.com/felixrieseberg/windows-build-tools#node-versions)

(What you are seeing is a JS syntax error for a statement that does ["destructuring assignment"](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Destructuring_assignment) which was implemented only in [node@6](https://node.green/#ES2015-syntax-destructuring--declarations)
