### ISSUE TITLE
Cannot install windows-build-tools

### ISSUE THREAD

**Issue by DingYea** [felixrieseberg/windows-build-tools#179]
I have tried to install windows-build-tools with yarn. It keep on installing but no response.

D:\>yarn global add node-gyp
yarn global v1.13.0
[1/4] Resolving packages...
[2/4] Fetching packages...
info fsevents@1.2.7: The platform "win32" is incompatible with this module.
info "fsevents@1.2.7" is an optional dependency and failed compatibility check. Excluding it from installation.
[3/4] Linking dependencies...
[4/4] Building fresh packages...
success Installed "node-gyp@3.8.0" with binaries:
      - node-gyp
Done in 5.04s.

D:\>yarn global add windows-build-tools
yarn global v1.13.0
[1/4] Resolving packages...
warning windows-build-tools > nugget > progress-stream > through2 > xtend > object-keys@0.4.0:
[2/4] Fetching packages...
info fsevents@1.2.7: The platform "win32" is incompatible with this module.
info "fsevents@1.2.7" is an optional dependency and failed compatibility check. Excluding it from installation.
[3/4] Linking dependencies...
[4/4] Building fresh packages...
[1/1] ⠐ windows-build-tools

The installation stays at this line for 2 hours already. Any advise? 
P.S. I am on window 10 and the PowerShell is run as administrator.

**Comment by jacobq** [comment]
Does the same thing happen if you install with `npm`? (Although `yarn` is supported, I have seen problems with it before.)

**Comment by DingYea** [comment]
I have tried npm and here below is the output:

D:\>npm install --global windows-build-tools

> windows-build-tools@5.1.0 postinstall C:\Users\tsangkl\AppData\Roaming\npm\node_modules\windows-build-tools
> node ./dist/index.js



Downloading python-2.7.15.amd64.msi
[>                                            ] 0.0% (0 B/s)
Downloaded python-2.7.15.amd64.msi. Saved to C:\Users\tsangkl\.windows-build-tools\python-2.7.15.amd64.msi.
Downloading vs_BuildTools.exe
[>                                            ] 0.0% (0 B/s)
Downloaded vs_BuildTools.exe. Saved to C:\Users\tsangkl\.windows-build-tools\vs_BuildTools.exe.

Starting installation...
Launched installers, now waiting for them to finish.
This will likely take some time - please be patient!

Status from the installers:
---------- Visual Studio Build Tools ----------
2019-03-21T15:55:04 : Verbose : [InstalledProductsProviderImpl]: Stream was closed
2019-03-21T15:55:04 : Verbose : [InstallerImpl]: Rpc connection was closed.
2019-03-21T15:55:04 : Verbose : [InstallerImpl]: Stream was closed
2019-03-21T15:55:04 : Verbose : [SetupUpdaterImpl]: Rpc connection was closed.
2019-03-21T15:55:04 : Verbose : [SetupUpdaterImpl]: Stream was closed
------------------- Python --------------------
Still waiting for installer log file...


Could not install Visual Studio Build Tools.
------------------------------------------------------------------------
I only find that the date modified of log file python-log.txt inside .windows-build-tools folder has been updated. However, the content is empty.
BTW, I PC is running behind proxy. I have no idea if it is the root cause. But I can npm / yarn other library with proxy setting.

**Comment by hieuhlc** [comment]
+1 Same here,

**Comment by luckywur** [comment]
+1

i use `npm install --global windows-build-tools@4.0.0` success

**Comment by hieuhlc** [comment]
> +1
> 
> i use `npm install --global windows-build-tools@4.0.0` success

I tried with both yarn and npm. After installed successfully the powershell still can't exit

**Comment by ankitgarg0006** [comment]
Use `npm install --global --production windows-build-tools --vs2015`. It worked for me.

**Comment by Tajnymag** [comment]
Yup, yarn installation doesn't work for me either. I get a "no binaries" message and the script exits immediately. It works with npm.

**Comment by pgupt** [comment]
> npm install --global windows-build-tools@4.0.0

this works.

**Comment by samshay** [comment]
> +1
> 
> i use `npm install --global windows-build-tools@4.0.0` success

Yeah, it's work

**Comment by sab-alex** [comment]
npm install --global windows-build-tools@4.0.0

**Comment by anhquande** [comment]
+1

**Comment by cqh52306** [comment]
+1

**Comment by hitontwo2** [comment]
hello guys its not working for me how can fix it i tryed all of them some times it shows bootstrapper stop working

**Comment by amilabandara** [comment]
Not working anymore. Got the same error as above

**Comment by olavomello** [comment]
Same here

**Comment by lukasalexanderweber** [comment]
Same here

**Comment by yairEO** [comment]
@amilabandara - if you're with VPN, try disconnecting it

**Comment by vahidrahmani** [comment]
> > +1
> > i use `npm install --global windows-build-tools@4.0.0` success
> 
> I tried with both yarn and npm. After installed successfully the powershell still can't exit

i use npm install --global windows-build-tools@4.0.0  . thank you from your help

**Comment by brunnoDatum** [comment]
npm install --global windows-build-tools@4.0.0

definitely, this one works... prod mode don't

**Comment by karlhorky** [comment]
Another option is to try installing the build tools via [Chocolatey](https://chocolatey.org/) instead (use an Administrator command line):

```sh
choco install python visualstudio2017-workload-vctools -y
npm config set msvs_version 2017
```

Maybe this should be documented in the readme as an alternative...

**Comment by JamesCullum** [comment]
With winget, you can use `winget install -e --id Microsoft.VisualStudio.2019.BuildTools`

**Comment by karlhorky** [comment]
Awesome! Is `winget` already included in the default installation of Windows 10? Or is it still something that requires the user to be part of some preview / beta program?

**Comment by JamesCullum** [comment]
Good point, it does not install python - which can be solved using `winget install -e --id Python.Python.3` (change to 2 at the end for python2).

At the time of writing it still requires to sign up to the insider program (automatically approved) and updating apps via the Windows Store a day later.

**Comment by karlhorky** [comment]
Cool, sounds good. Look forward to winget being standard!

Maybe if you update your original command above to include both, it would be helpful for people finding this via search engines and copy-pasting.

**Comment by MichaelMagdyG** [comment]
Error
How to fix
$ npm install --global windows-build-tools


2021-07-04T22_04_08_032Z-debug.log

0 info it worked if it ends with ok
1 verbose cli [
1 verbose cli   'C:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'install',
1 verbose cli   '--global',
1 verbose cli   'windows-build-tools'
1 verbose cli ]
2 info using npm@6.14.4
3 info using node@v12.18.0
4 verbose npm-session a5e0e42a628073da
5 silly install loadCurrentTree
6 silly install readGlobalPackageData
7 http fetch GET 304 http://registry.npmjs.org/windows-build-tools 1013ms (from cache)
8 silly pacote tag manifest for windows-build-tools@latest fetched in 1203ms
9 timing stage:loadCurrentTree Completed in 1433ms
10 silly install loadIdealTree
11 silly install cloneCurrentTreeToIdealTree
12 timing stage:loadIdealTree:cloneCurrentTree Completed in 2ms
13 silly install loadShrinkwrap
14 timing stage:loadIdealTree:loadShrinkwrap Completed in 13ms
15 silly install loadAllDepsIntoIdealTree
16 silly resolveWithNewModule windows-build-tools@5.2.2 checking installable status
17 http fetch GET 304 http://registry.npmjs.org/chalk 1180ms (from cache)
18 silly pacote range manifest for chalk@^2.4.2 fetched in 1252ms
19 silly resolveWithNewModule chalk@2.4.2 checking installable status
20 http fetch GET 304 http://registry.npmjs.org/nugget 1571ms (from cache)
21 http fetch GET 304 http://registry.npmjs.org/in-gfw 1742ms (from cache)
22 silly pacote range manifest for nugget@^2.0.1 fetched in 1849ms
23 silly resolveWithNewModule nugget@2.0.1 checking installable status
24 silly pacote range manifest for in-gfw@^1.2.0 fetched in 1947ms
25 silly resolveWithNewModule in-gfw@1.2.0 checking installable status
26 http fetch GET 304 http://registry.npmjs.org/string-width 1885ms (from cache)
27 silly pacote range manifest for string-width@^4.1.0 fetched in 1979ms
28 silly resolveWithNewModule string-width@4.2.2 checking installable status
29 http fetch GET 304 http://registry.npmjs.org/debug 2290ms (from cache)
30 http fetch GET 304 http://registry.npmjs.org/fs-extra 2293ms (from cache)
31 silly pacote range manifest for debug@^4.1.1 fetched in 2354ms
32 silly resolveWithNewModule debug@4.3.2 checking installable status
33 silly pacote range manifest for fs-extra@^8.0.1 fetched in 2354ms
34 silly resolveWithNewModule fs-extra@8.1.0 checking installable status
35 http fetch GET 304 http://registry.npmjs.org/escape-string-regexp 1194ms (from cache)
36 silly pacote range manifest for escape-string-regexp@^1.0.5 fetched in 1235ms
37 silly resolveWithNewModule escape-string-regexp@1.0.5 checking installable status
38 http fetch GET 304 http://registry.npmjs.org/supports-color 2447ms (from cache)
39 silly pacote range manifest for supports-color@^5.3.0 fetched in 2461ms
40 silly resolveWithNewModule supports-color@5.5.0 checking installable status
41 http fetch GET 304 http://registry.npmjs.org/ansi-styles 3681ms (from cache)
42 silly pacote range manifest for ansi-styles@^3.2.1 fetched in 3693ms
43 silly resolveWithNewModule ansi-styles@3.2.1 checking installable status
44 http fetch GET 200 http://registry.npmjs.org/color-convert 82ms (from cache)
45 silly pacote range manifest for color-convert@^1.9.0 fetched in 104ms
46 silly resolveWithNewModule color-convert@1.9.3 checking installable status
47 http fetch GET 304 http://registry.npmjs.org/color-name 334ms (from cache)
48 silly pacote version manifest for color-name@1.1.3 fetched in 382ms
49 silly resolveWithNewModule color-name@1.1.3 checking installable status
50 http fetch GET 304 http://registry.npmjs.org/has-flag 433ms (from cache)
51 silly pacote range manifest for has-flag@^3.0.0 fetched in 473ms
52 silly resolveWithNewModule has-flag@3.0.0 checking installable status
53 http fetch GET 304 http://registry.npmjs.org/ms 381ms (from cache)
54 silly pacote version manifest for ms@2.1.2 fetched in 389ms
55 silly resolveWithNewModule ms@2.1.2 checking installable status
56 http fetch GET 304 http://registry.npmjs.org/jsonfile 415ms (from cache)
57 http fetch GET 304 http://registry.npmjs.org/graceful-fs 433ms (from cache)
58 silly pacote range manifest for jsonfile@^4.0.0 fetched in 451ms
59 silly resolveWithNewModule jsonfile@4.0.0 checking installable status
60 silly pacote range manifest for graceful-fs@^4.2.0 fetched in 471ms
61 silly resolveWithNewModule graceful-fs@4.2.6 checking installable status
62 http fetch GET 304 http://registry.npmjs.org/universalify 9059ms (from cache)
63 silly pacote range manifest for universalify@^0.1.0 fetched in 9075ms
64 silly resolveWithNewModule universalify@0.1.2 checking installable status
65 http fetch GET 304 http://registry.npmjs.org/glob 506ms (from cache)
66 silly pacote range manifest for glob@^7.1.2 fetched in 522ms
67 silly resolveWithNewModule glob@7.1.7 checking installable status
68 http fetch GET 304 http://registry.npmjs.org/is-wsl 5713ms (from cache)
69 http fetch GET 304 http://registry.npmjs.org/mem 5719ms (from cache)
70 silly pacote range manifest for is-wsl@^1.1.0 fetched in 5733ms
71 silly resolveWithNewModule is-wsl@1.1.0 checking installable status
72 silly pacote range manifest for mem@^3.0.1 fetched in 5735ms
73 silly resolveWithNewModule mem@3.0.1 checking installable status
74 http fetch GET 304 http://registry.npmjs.org/fs.realpath 497ms (from cache)
75 http fetch GET 304 http://registry.npmjs.org/inflight 493ms (from cache)
76 http fetch GET 304 http://registry.npmjs.org/once 501ms (from cache)
77 silly pacote range manifest for fs.realpath@^1.0.0 fetched in 513ms
78 silly resolveWithNewModule fs.realpath@1.0.0 checking installable status
79 http fetch GET 304 http://registry.npmjs.org/minimatch 518ms (from cache)
80 silly pacote range manifest for inflight@^1.0.4 fetched in 525ms
81 silly resolveWithNewModule inflight@1.0.6 checking installable status
82 http fetch GET 304 http://registry.npmjs.org/path-is-absolute 513ms (from cache)
83 silly pacote range manifest for once@^1.3.0 fetched in 532ms
84 silly resolveWithNewModule once@1.4.0 checking installable status
85 silly pacote range manifest for minimatch@^3.0.4 fetched in 535ms
86 silly resolveWithNewModule minimatch@3.0.4 checking installable status
87 silly pacote range manifest for path-is-absolute@^1.0.0 fetched in 530ms
88 silly resolveWithNewModule path-is-absolute@1.0.1 checking installable status
89 http fetch GET 304 http://registry.npmjs.org/inherits 5315ms (from cache)
90 silly pacote range manifest for inherits@2 fetched in 5321ms
91 silly resolveWithNewModule inherits@2.0.4 checking installable status
92 http fetch GET 304 http://registry.npmjs.org/wrappy 1520ms (from cache)
93 silly pacote range manifest for wrappy@1 fetched in 1530ms
94 silly resolveWithNewModule wrappy@1.0.2 checking installable status
95 http fetch GET 304 http://registry.npmjs.org/brace-expansion 770ms (from cache)
96 silly pacote range manifest for brace-expansion@^1.1.7 fetched in 781ms
97 silly resolveWithNewModule brace-expansion@1.1.11 checking installable status
98 http fetch GET 304 http://registry.npmjs.org/concat-map 780ms (from cache)
99 silly pacote version manifest for concat-map@0.0.1 fetched in 858ms
100 silly resolveWithNewModule concat-map@0.0.1 checking installable status
101 http fetch GET 304 http://registry.npmjs.org/balanced-match 1107ms (from cache)
102 silly pacote range manifest for balanced-match@^1.0.0 fetched in 1119ms
103 silly resolveWithNewModule balanced-match@1.0.2 checking installable status
104 http fetch GET 304 http://registry.npmjs.org/p-is-promise 739ms (from cache)
105 silly pacote range manifest for p-is-promise@^1.1.0 fetched in 754ms
106 silly resolveWithNewModule p-is-promise@1.1.0 checking installable status
107 http fetch GET 304 http://registry.npmjs.org/mimic-fn 13910ms (from cache)
108 silly pacote range manifest for mimic-fn@^1.0.0 fetched in 13941ms
109 silly resolveWithNewModule mimic-fn@1.2.0 checking installable status
110 silly pacote range manifest for debug@^2.1.3 fetched in 468ms
111 silly resolveWithNewModule debug@2.6.9 checking installable status
112 http fetch GET 304 http://registry.npmjs.org/progress-stream 1306ms (from cache)
113 silly pacote range manifest for progress-stream@^1.1.0 fetched in 1336ms
114 silly resolveWithNewModule progress-stream@1.2.0 checking installable status
115 http fetch GET 304 http://registry.npmjs.org/request 1967ms (from cache)
116 http fetch GET 304 http://registry.npmjs.org/single-line-log 1988ms (from cache)
117 silly pacote range manifest for request@^2.45.0 fetched in 2269ms
118 warn deprecated request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142
119 silly resolveWithNewModule request@2.88.2 checking installable status
120 silly pacote range manifest for single-line-log@^1.1.2 fetched in 2285ms
121 silly resolveWithNewModule single-line-log@1.1.2 checking installable status
122 http fetch GET 304 http://registry.npmjs.org/throttleit 2752ms (from cache)
123 silly pacote version manifest for throttleit@0.0.2 fetched in 2786ms
124 silly resolveWithNewModule throttleit@0.0.2 checking installable status
125 http fetch GET 304 http://registry.npmjs.org/minimist 5662ms (from cache)
126 silly pacote range manifest for minimist@^1.1.0 fetched in 5687ms
127 silly resolveWithNewModule minimist@1.2.5 checking installable status
128 http fetch GET 304 http://registry.npmjs.org/pretty-bytes 6429ms (from cache)
129 silly pacote range manifest for pretty-bytes@^1.0.2 fetched in 6497ms
130 silly resolveWithNewModule pretty-bytes@1.0.4 checking installable status
131 silly pacote version manifest for ms@2.0.0 fetched in 13ms
132 silly resolveWithNewModule ms@2.0.0 checking installable status
133 http fetch GET 304 http://registry.npmjs.org/meow 487ms (from cache)
134 silly pacote range manifest for meow@^3.1.0 fetched in 503ms
135 silly resolveWithNewModule meow@3.7.0 checking installable status
136 http fetch GET 304 http://registry.npmjs.org/get-stdin 32353ms attempt #2 (from cache)
137 silly pacote range manifest for get-stdin@^4.0.1 fetched in 32383ms
138 silly resolveWithNewModule get-stdin@4.0.1 checking installable status
139 http fetch GET 200 http://registry.npmjs.org/map-obj 1202ms (from cache)
140 silly pacote range manifest for map-obj@^1.0.1 fetched in 1361ms
141 silly resolveWithNewModule map-obj@1.0.1 checking installable status
142 http fetch GET 304 http://registry.npmjs.org/camelcase-keys 1806ms (from cache)
143 silly pacote range manifest for camelcase-keys@^2.0.0 fetched in 1817ms
144 silly resolveWithNewModule camelcase-keys@2.1.0 checking installable status
145 http fetch GET 304 http://registry.npmjs.org/decamelize 1931ms (from cache)
146 silly pacote range manifest for decamelize@^1.1.2 fetched in 1960ms
147 silly resolveWithNewModule decamelize@1.2.0 checking installable status
148 http fetch GET 304 http://registry.npmjs.org/object-assign 2439ms (from cache)
149 http fetch GET 304 http://registry.npmjs.org/normalize-package-data 2462ms (from cache)
150 http fetch GET 304 http://registry.npmjs.org/read-pkg-up 2458ms (from cache)
151 silly pacote range manifest for object-assign@^4.0.1 fetched in 2464ms
152 silly resolveWithNewModule object-assign@4.1.1 checking installable status
153 silly pacote range manifest for normalize-package-data@^2.3.4 fetched in 2620ms
154 silly resolveWithNewModule normalize-package-data@2.5.0 checking installable status
155 silly pacote range manifest for read-pkg-up@^1.0.1 fetched in 2622ms
156 silly resolveWithNewModule read-pkg-up@1.0.1 checking installable status
157 http fetch GET 304 http://registry.npmjs.org/redent 2773ms (from cache)
158 silly pacote range manifest for redent@^1.0.0 fetched in 2784ms
159 silly resolveWithNewModule redent@1.0.0 checking installable status
160 http fetch GET 304 http://registry.npmjs.org/trim-newlines 2784ms (from cache)
161 silly pacote range manifest for trim-newlines@^1.0.0 fetched in 2790ms
162 silly resolveWithNewModule trim-newlines@1.0.0 checking installable status
163 http fetch GET 304 http://registry.npmjs.org/loud-rejection 3120ms (from cache)
164 silly pacote range manifest for loud-rejection@^1.0.0 fetched in 3196ms
165 silly resolveWithNewModule loud-rejection@1.6.0 checking installable status
166 http fetch GET 304 http://registry.npmjs.org/camelcase 531ms (from cache)
167 silly pacote range manifest for camelcase@^2.0.0 fetched in 554ms
168 silly resolveWithNewModule camelcase@2.1.1 checking installable status
169 http fetch GET 304 http://registry.npmjs.org/signal-exit 805ms (from cache)
170 silly pacote range manifest for signal-exit@^3.0.0 fetched in 813ms
171 silly resolveWithNewModule signal-exit@3.0.3 checking installable status
172 http fetch GET 304 http://registry.npmjs.org/currently-unhandled 1254ms (from cache)
173 silly pacote range manifest for currently-unhandled@^0.4.1 fetched in 1410ms
174 silly resolveWithNewModule currently-unhandled@0.4.1 checking installable status
175 http fetch GET 304 http://registry.npmjs.org/array-find-index 719ms (from cache)
176 silly pacote range manifest for array-find-index@^1.0.1 fetched in 725ms
177 silly resolveWithNewModule array-find-index@1.0.2 checking installable status
178 http fetch GET 304 http://registry.npmjs.org/validate-npm-package-license 907ms (from cache)
179 silly pacote range manifest for validate-npm-package-license@^3.0.1 fetched in 984ms
180 silly resolveWithNewModule validate-npm-package-license@3.0.4 checking installable status
181 http fetch GET 304 http://registry.npmjs.org/semver 1365ms (from cache)
182 silly pacote range manifest for semver@2 || 3 || 4 || 5 fetched in 1432ms
183 silly resolveWithNewModule semver@5.7.1 checking installable status
184 http fetch GET 304 http://registry.npmjs.org/resolve 1462ms (from cache)
185 silly pacote range manifest for resolve@^1.10.0 fetched in 1492ms
186 silly resolveWithNewModule resolve@1.20.0 checking installable status
187 http fetch GET 304 http://registry.npmjs.org/hosted-git-info 2816ms (from cache)
188 silly pacote range manifest for hosted-git-info@^2.1.4 fetched in 3085ms
189 silly resolveWithNewModule hosted-git-info@2.8.9 checking installable status
190 http fetch GET 304 http://registry.npmjs.org/path-parse 666ms (from cache)
191 silly pacote range manifest for path-parse@^1.0.6 fetched in 771ms
192 silly resolveWithNewModule path-parse@1.0.7 checking installable status
193 http fetch GET 304 http://registry.npmjs.org/is-core-module 2967ms (from cache)
194 silly pacote range manifest for is-core-module@^2.2.0 fetched in 2978ms
195 silly resolveWithNewModule is-core-module@2.4.0 checking installable status
196 http fetch GET 304 http://registry.npmjs.org/has 481ms (from cache)
197 silly pacote range manifest for has@^1.0.3 fetched in 627ms
198 silly resolveWithNewModule has@1.0.3 checking installable status
199 http fetch GET 304 http://registry.npmjs.org/function-bind 259ms (from cache)
200 silly pacote range manifest for function-bind@^1.1.1 fetched in 329ms
201 silly resolveWithNewModule function-bind@1.1.1 checking installable status
202 http fetch GET 304 http://registry.npmjs.org/spdx-expression-parse 767ms (from cache)
203 http fetch GET 304 http://registry.npmjs.org/spdx-correct 924ms (from cache)
204 silly pacote range manifest for spdx-expression-parse@^3.0.0 fetched in 925ms
205 silly resolveWithNewModule spdx-expression-parse@3.0.1 checking installable status
206 silly pacote range manifest for spdx-correct@^3.0.0 fetched in 937ms
207 silly resolveWithNewModule spdx-correct@3.1.1 checking installable status
208 http fetch GET 304 http://registry.npmjs.org/spdx-license-ids 19776ms attempt #2 (from cache)
209 silly pacote range manifest for spdx-license-ids@^3.0.0 fetched in 19786ms
210 silly resolveWithNewModule spdx-license-ids@3.0.9 checking installable status
211 http fetch GET 200 http://registry.npmjs.org/spdx-exceptions 31ms (from cache)
212 silly pacote range manifest for spdx-exceptions@^2.1.0 fetched in 31ms
213 silly resolveWithNewModule spdx-exceptions@2.3.0 checking installable status
214 http fetch GET 304 http://registry.npmjs.org/find-up 251ms (from cache)
215 silly pacote range manifest for find-up@^1.0.0 fetched in 267ms
216 silly resolveWithNewModule find-up@1.1.2 checking installable status
217 http fetch GET 304 http://registry.npmjs.org/read-pkg 844ms (from cache)
218 silly pacote range manifest for read-pkg@^1.0.0 fetched in 844ms
219 silly resolveWithNewModule read-pkg@1.1.0 checking installable status
220 http fetch GET 304 http://registry.npmjs.org/path-exists 340ms (from cache)
221 silly pacote range manifest for path-exists@^2.0.0 fetched in 346ms
222 silly resolveWithNewModule path-exists@2.1.0 checking installable status
223 http fetch GET 304 http://registry.npmjs.org/pinkie-promise 355ms (from cache)
224 silly pacote range manifest for pinkie-promise@^2.0.0 fetched in 359ms
225 silly resolveWithNewModule pinkie-promise@2.0.1 checking installable status
226 http fetch GET 304 http://registry.npmjs.org/pinkie 219ms (from cache)
227 silly pacote range manifest for pinkie@^2.0.0 fetched in 235ms
228 silly resolveWithNewModule pinkie@2.0.4 checking installable status
229 http fetch GET 304 http://registry.npmjs.org/path-type 5073ms (from cache)
230 silly pacote range manifest for path-type@^1.0.0 fetched in 5073ms
231 silly resolveWithNewModule path-type@1.1.0 checking installable status
232 http fetch GET 304 http://registry.npmjs.org/load-json-file 5946ms (from cache)
233 silly pacote range manifest for load-json-file@^1.0.0 fetched in 5962ms
234 silly resolveWithNewModule load-json-file@1.1.0 checking installable status
235 http fetch GET 304 http://registry.npmjs.org/pify 296ms (from cache)
236 silly pacote range manifest for pify@^2.0.0 fetched in 312ms
237 silly resolveWithNewModule pify@2.3.0 checking installable status
238 http fetch GET 304 http://registry.npmjs.org/parse-json 312ms (from cache)
239 silly pacote range manifest for parse-json@^2.2.0 fetched in 327ms
240 silly resolveWithNewModule parse-json@2.2.0 checking installable status
241 http fetch GET 304 http://registry.npmjs.org/strip-bom 452ms (from cache)
242 silly pacote range manifest for strip-bom@^2.0.0 fetched in 468ms
243 silly resolveWithNewModule strip-bom@2.0.0 checking installable status
244 http fetch GET 304 http://registry.npmjs.org/error-ex 218ms (from cache)
245 silly pacote range manifest for error-ex@^1.2.0 fetched in 234ms
246 silly resolveWithNewModule error-ex@1.3.2 checking installable status
247 http fetch GET 304 http://registry.npmjs.org/is-arrayish 780ms (from cache)
248 silly pacote range manifest for is-arrayish@^0.2.1 fetched in 795ms
249 silly resolveWithNewModule is-arrayish@0.2.1 checking installable status
250 http fetch GET 304 http://registry.npmjs.org/is-utf8 845ms (from cache)
251 silly pacote range manifest for is-utf8@^0.2.0 fetched in 861ms
252 silly resolveWithNewModule is-utf8@0.2.1 checking installable status
253 http fetch GET 304 http://registry.npmjs.org/strip-indent 343ms (from cache)
254 http fetch GET 304 http://registry.npmjs.org/indent-string 359ms (from cache)
255 silly pacote range manifest for strip-indent@^1.0.1 fetched in 343ms
256 silly resolveWithNewModule strip-indent@1.0.1 checking installable status
257 silly pacote range manifest for indent-string@^2.1.0 fetched in 375ms
258 silly resolveWithNewModule indent-string@2.1.0 checking installable status
259 http fetch GET 304 http://registry.npmjs.org/repeating 3276ms (from cache)
260 silly pacote range manifest for repeating@^2.0.0 fetched in 3291ms
261 silly resolveWithNewModule repeating@2.0.1 checking installable status
262 http fetch GET 304 http://registry.npmjs.org/is-finite 645ms (from cache)
263 silly pacote range manifest for is-finite@^1.0.0 fetched in 652ms
264 silly resolveWithNewModule is-finite@1.1.0 checking installable status
265 http fetch GET 304 http://registry.npmjs.org/through2 458ms (from cache)
266 silly pacote range manifest for through2@~0.2.3 fetched in 475ms
267 silly resolveWithNewModule through2@0.2.3 checking installable status
268 http fetch GET 304 http://registry.npmjs.org/speedometer 487ms (from cache)
269 silly pacote range manifest for speedometer@~0.1.2 fetched in 487ms
270 silly resolveWithNewModule speedometer@0.1.4 checking installable status
271 http fetch GET 200 http://registry.npmjs.org/readable-stream 54ms (from cache)
272 silly pacote range manifest for readable-stream@~1.1.9 fetched in 70ms
273 silly resolveWithNewModule readable-stream@1.1.14 checking installable status
274 http fetch GET 304 http://registry.npmjs.org/xtend 320ms (from cache)
275 silly pacote range manifest for xtend@~2.1.1 fetched in 335ms
276 silly resolveWithNewModule xtend@2.1.2 checking installable status
277 http fetch GET 304 http://registry.npmjs.org/isarray 737ms (from cache)
278 http fetch GET 304 http://registry.npmjs.org/core-util-is 758ms (from cache)
279 silly pacote version manifest for isarray@0.0.1 fetched in 738ms
280 silly resolveWithNewModule isarray@0.0.1 checking installable status
281 silly pacote range manifest for core-util-is@~1.0.0 fetched in 774ms
282 silly resolveWithNewModule core-util-is@1.0.2 checking installable status
283 http fetch GET 304 http://registry.npmjs.org/string_decoder 750ms (from cache)
284 silly pacote range manifest for string_decoder@~0.10.x fetched in 766ms
285 silly resolveWithNewModule string_decoder@0.10.31 checking installable status
286 http fetch GET 304 http://registry.npmjs.org/object-keys 221ms (from cache)
287 silly pacote range manifest for object-keys@~0.4.0 fetched in 236ms
288 silly resolveWithNewModule object-keys@0.4.0 checking installable status
289 http fetch GET 304 http://registry.npmjs.org/aws-sign2 468ms (from cache)
290 silly pacote range manifest for aws-sign2@~0.7.0 fetched in 468ms
291 silly resolveWithNewModule aws-sign2@0.7.0 checking installable status
292 http fetch GET 304 http://registry.npmjs.org/caseless 484ms (from cache)
293 http fetch GET 304 http://registry.npmjs.org/aws4 484ms (from cache)
294 silly fetchPackageMetaData error for aws4@^1.8.0 Unexpected end of JSON input while parsing near '...,"devDependencies":{"'
295 silly pacote range manifest for caseless@~0.12.0 fetched in 515ms
296 silly resolveWithNewModule caseless@0.12.0 checking installable status
297 http fetch GET 304 http://registry.npmjs.org/forever-agent 983ms (from cache)
298 http fetch GET 304 http://registry.npmjs.org/har-validator 983ms (from cache)
299 http fetch GET 304 http://registry.npmjs.org/form-data 999ms (from cache)
300 http fetch GET 304 http://registry.npmjs.org/combined-stream 1014ms (from cache)
301 http fetch GET 304 http://registry.npmjs.org/http-signature 1030ms (from cache)
302 silly pacote range manifest for forever-agent@~0.6.1 fetched in 1046ms
303 silly resolveWithNewModule forever-agent@0.6.1 checking installable status
304 silly pacote range manifest for har-validator@~5.1.3 fetched in 1046ms
305 warn deprecated har-validator@5.1.5: this library is no longer supported
306 silly resolveWithNewModule har-validator@5.1.5 checking installable status
307 silly pacote range manifest for form-data@~2.3.2 fetched in 1077ms
308 silly resolveWithNewModule form-data@2.3.3 checking installable status
309 silly pacote range manifest for combined-stream@~1.0.6 fetched in 1092ms
310 silly resolveWithNewModule combined-stream@1.0.8 checking installable status
311 http fetch GET 304 http://registry.npmjs.org/isstream 655ms (from cache)
312 silly pacote range manifest for http-signature@~1.2.0 fetched in 1139ms
313 silly resolveWithNewModule http-signature@1.2.0 checking installable status
314 http fetch GET 304 http://registry.npmjs.org/json-stringify-safe 718ms (from cache)
315 http fetch GET 304 http://registry.npmjs.org/mime-types 733ms (from cache)
316 silly pacote range manifest for isstream@~0.1.2 fetched in 764ms
317 silly resolveWithNewModule isstream@0.1.2 checking installable status
318 silly pacote range manifest for json-stringify-safe@~5.0.1 fetched in 796ms
319 silly resolveWithNewModule json-stringify-safe@5.0.1 checking installable status
320 silly pacote range manifest for mime-types@~2.1.19 fetched in 796ms
321 silly resolveWithNewModule mime-types@2.1.31 checking installable status
322 http fetch GET 304 http://registry.npmjs.org/extend 1341ms (from cache)
323 http fetch GET 304 http://registry.npmjs.org/is-typedarray 1358ms (from cache)
324 silly pacote range manifest for extend@~3.0.2 fetched in 1373ms
325 silly resolveWithNewModule extend@3.0.2 checking installable status
326 silly pacote range manifest for is-typedarray@~1.0.0 fetched in 1436ms
327 silly resolveWithNewModule is-typedarray@1.0.0 checking installable status
328 http fetch GET 304 http://registry.npmjs.org/oauth-sign 452ms (from cache)
329 silly pacote range manifest for oauth-sign@~0.9.0 fetched in 468ms
330 silly resolveWithNewModule oauth-sign@0.9.0 checking installable status
331 http fetch GET 304 http://registry.npmjs.org/performance-now 499ms (from cache)
332 silly pacote range manifest for performance-now@^2.1.0 fetched in 577ms
333 silly resolveWithNewModule performance-now@2.1.0 checking installable status
334 http fetch GET 304 http://registry.npmjs.org/tunnel-agent 531ms (from cache)
335 http fetch GET 304 http://registry.npmjs.org/qs 686ms (from cache)
336 http fetch GET 304 http://registry.npmjs.org/safe-buffer 702ms (from cache)
337 silly pacote range manifest for tunnel-agent@^0.6.0 fetched in 577ms
338 silly resolveWithNewModule tunnel-agent@0.6.0 checking installable status
339 http fetch GET 304 http://registry.npmjs.org/uuid 530ms (from cache)
340 http fetch GET 304 http://registry.npmjs.org/tough-cookie 671ms (from cache)
341 silly pacote range manifest for qs@~6.5.2 fetched in 811ms
342 silly resolveWithNewModule qs@6.5.2 checking installable status
343 silly pacote range manifest for safe-buffer@^5.1.2 fetched in 796ms
344 silly resolveWithNewModule safe-buffer@5.2.1 checking installable status
345 silly pacote range manifest for uuid@^3.3.2 fetched in 624ms
346 warn deprecated uuid@3.4.0: Please upgrade  to version 7 or higher.  Older versions may use Math.random() in certain circumstances, which is known to be problematic.  See https://v8.dev/blog/math-random for details.
347 silly resolveWithNewModule uuid@3.4.0 checking installable status
348 silly pacote range manifest for tough-cookie@~2.5.0 fetched in 765ms
349 silly resolveWithNewModule tough-cookie@2.5.0 checking installable status
350 timing stage:rollbackFailedOptional Completed in 15ms
351 timing stage:runTopLevelLifecycles Completed in 138830ms
352 verbose stack SyntaxError: Unexpected end of JSON input while parsing near '...,"devDependencies":{"'
352 verbose stack     at JSON.parse (<anonymous>)
352 verbose stack     at parseJson (C:\Program Files\nodejs\node_modules\npm\node_modules\json-parse-better-errors\index.js:7:17)
352 verbose stack     at C:\Program Files\nodejs\node_modules\npm\node_modules\node-fetch-npm\src\body.js:96:50
352 verbose stack     at runMicrotasks (<anonymous>)
352 verbose stack     at processTicksAndRejections (internal/process/task_queues.js:97:5)
353 verbose cwd C:\Users\Michael
354 verbose Windows_NT 6.1.7601
355 verbose argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "--global" "windows-build-tools"
356 verbose node v12.18.0
357 verbose npm  v6.14.4
358 error Unexpected end of JSON input while parsing near '...,"devDependencies":{"'
359 verbose exit [ 1, true ]
