### ISSUE TITLE
gyp ERR! stack Error: `C:\Program Files (x86)\MSBuild\14.0\bin\MSBuild.exe` failed with exit code: 1

### ISSUE THREAD

**Issue by thisTom** [felixrieseberg/windows-build-tools#193]
gyp ERR! build error
gyp ERR! stack Error: `C:\Program Files (x86)\MSBuild\14.0\bin\MSBuild.exe` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onExit (C:\Users\SNQU\AppData\Roaming\npm\node_modules\node-gyp\lib\build.js:196:23)
gyp ERR! stack     at ChildProcess.emit (events.js:198:13)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:248:12)
gyp ERR! System Windows_NT 10.0.17134
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\SNQU\\AppData\\Roaming\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd F:\www\zuhao\client\node_modules\ffi
gyp ERR! node -v v10.16.0
gyp ERR! node-gyp -v v5.0.3
gyp ERR! not ok

realy need help  thanks!

**Comment by cpp1992** [comment]
I am dealing with this problem for two weeks....wtf...

**Comment by dtbenson43** [comment]
rerun your installation with --verbose

**Comment by tarun-nagpal-github** [comment]
Hey Guys,

I am getting the same error. Below is the details with verbose 


` Release\obj\z\zutil.obj
  Release\obj\z\win_delay_load_hook.obj
  z.vcxproj -> D:\projects\HFH\frontend-portal\node_modules\grpc\build\Release\\libz.lib
FinalizeBuildStatus:
  Deleting file "Release\obj\z\z.tlog\unsuccessfulbuild".
  Touching "Release\obj\z\z.tlog\z.lastbuildstate".
Done Building Project "D:\projects\HFH\frontend-portal\node_modules\grpc\build\z.vcxproj" (default targets).
Done Building Project "D:\projects\HFH\frontend-portal\node_modules\grpc\build\binding.sln" (default targets) -- FAILED.

Build FAILED.

"D:\projects\HFH\frontend-portal\node_modules\grpc\build\binding.sln" (default target) (1) ->
"D:\projects\HFH\frontend-portal\node_modules\grpc\build\boringssl.vcxproj" (default target) (3) ->
(ClCompile target) ->
  d:\projects\hfh\frontend-portal\node_modules\grpc\deps\grpc\third_party\boringssl\include\openssl\base.h(143): warning C4005: 'OPENSSL_THREADS': macro redefinition (compiling source file ..\deps\grpc\src\boringssl\err_data.c) [D:\projects\HFH\frontend-portal\node_modules\grpc\build\boringssl.vcxproj]
  d:\projects\hfh\frontend-portal\node_modules\grpc\deps\grpc\third_party\boringssl\include\openssl\base.h(147): warning C4005: 'OPENSSL_VERSION_NUMBER': macro redefinition (compiling source file ..\deps\grpc\src\boringssl\err_data.c) [D:\projects\HFH\frontend-portal\node_modules\grpc\build\boringssl.vcxproj]
  c:\users\tarun.nagpal\.node-gyp\12.13.0\include\node\openssl\e_os2.h(171): warning C4005: 'OPENSSL_EXPORT': macro redefinition (compiling source file ..\deps\grpc\src\boringssl\err_data.c) [D:\projects\HFH\frontend-portal\node_modules\grpc\build\boringssl.vcxproj]
  d:\projects\hfh\frontend-portal\node_modules\grpc\deps\grpc\third_party\boringssl\include\openssl\base.h(143): warning C4005: 'OPENSSL_THREADS': macro redefinition (compiling source file ..\deps\grpc\third_party\boringssl\crypto\asn1\a_d2i_fp.c) [D:\projects\HFH\frontend-portal\node_modules\grpc\build\boringssl.vcxproj]
  d:\projects\hfh\frontend-portal\node_modules\grpc\deps\grpc\third_party\boringssl\include\openssl\base.h(143): warning C4005: 'OPENSSL_THREADS': macro redefinition (compiling source file ..\deps\grpc\third_party\boringssl\crypto\asn1\a_bool.c) [D:\projects\HFH\frontend-portal\node_modules\grpc\build\boringssl.vcxproj]
  d:\projects\hfh\frontend-portal\node_modules\grpc\deps\grpc\third_party\boringssl\include\openssl\base.h(147): warning C4005: 'OPENSSL_VERSION_NUMBER': macro redefinition (compiling source file ..\deps\grpc\third_party\boringssl\crypto\asn1\a_d2i_fp.c) [D:\projects\HFH\frontend-portal\node_modules\grpc\build\boringssl.vcxproj]
  d:\projects\hfh\frontend-portal\node_modules\grpc\deps\grpc\third_party\boringssl\include\openssl\base.h(147): warning C4005: 'OPENSSL_VERSION_NUMBER': macro redefinition (compiling source file ..\deps\grpc\third_party\boringssl\crypto\asn1\a_bool.c) [D:\projects\HFH\frontend-portal\node_modules\grpc\build\boringssl.vcxproj]
  d:\projects\hfh\frontend-portal\node_modules\grpc\deps\grpc\third_party\boringssl\include\openssl\base.h(182): warning C4005: 'OPENSSL_EXPORT': macro redefinition (compiling source file ..\deps\grpc\third_party\boringssl\crypto\asn1\a_d2i_fp.c) [D:\projects\HFH\frontend-portal\node_modules\grpc\build\boringssl.vcxproj]
  d:\projects\hfh\frontend-portal\node_modules\grpc\deps\grpc\third_party\boringssl\include\openssl\base.h(182): warning C4005: 'OPENSSL_EXPORT': macro redefinition (compiling source file ..\deps\grpc\third_party\boringssl\crypto\asn1\a_bool.c) [D:\projects\HFH\frontend-portal\node_modules\grpc\build\boringssl.vcxproj]
  d:\projects\hfh\frontend-portal\node_modules\grpc\deps\grpc\third_party\boringssl\include\openssl\mem.h(79): warning C4030: first formal parameter list longer than the second list (compiling source file ..\deps\grpc\third_party\boringssl\crypto\asn1\a_bool.c) [D:\projects\HFH\frontend-portal\node_modules\grpc\build\boringssl.vcxproj]
  d:\projects\hfh\frontend-portal\node_modules\grpc\deps\grpc\third_party\boringssl\include\openssl\mem.h(83): warning C4030: first formal parameter list longer than the second list (compiling source file ..\deps\grpc\third_party\boringssl\crypto\asn1\a_bool.c) [D:\projects\HFH\frontend-portal\node_modules\grpc\build\boringssl.vcxproj]
  d:\projects\hfh\frontend-portal\node_modules\grpc\deps\grpc\third_party\boringssl\include\openssl\mem.h(88): warning C4030: first formal parameter list longer than the second list (compiling source file ..\deps\grpc\third_party\boringssl\crypto\asn1\a_bool.c) [D:\projects\HFH\frontend-portal\node_modules\grpc\build\boringssl.vcxproj]
  d:\projects\hfh\frontend-portal\node_modules\grpc\deps\grpc\third_party\boringssl\include\openssl\mem.h(105): warning C4030: first formal parameter list longer than the second list (compiling source file ..\deps\grpc\third_party\boringssl\crypto\asn1\a_bool.c) [D:\projects\HFH\frontend-portal\node_modules\grpc\build\boringssl.vcxproj]
  d:\projects\hfh\frontend-portal\node_modules\grpc\deps\grpc\third_party\boringssl\include\openssl\mem.h(79): warning C4030: first formal parameter list longer than the second list (compiling source file ..\deps\grpc\third_party\boringssl\crypto\asn1\a_d2i_fp.c) [D:\projects\HFH\frontend-portal\node_modules\grpc\build\boringssl.vcxproj]
  d:\projects\hfh\frontend-portal\node_modules\grpc\deps\grpc\third_party\boringssl\crypto\asn1\a_bool.c(108): warning C4013: 'OPENSSL_PUT_ERROR' undefined; assuming extern returning int [D:\projects\HFH\frontend-portal\node_modules\grpc\build\boringssl.vcxproj]
  d:\projects\hfh\frontend-portal\node_modules\grpc\deps\grpc\third_party\boringssl\include\openssl\mem.h(83): warning C4030: first formal parameter list longer than the second list (compiling source file ..\deps\grpc\third_party\boringssl\crypto\asn1\a_d2i_fp.c) [D:\projects\HFH\frontend-portal\node_modules\grpc\build\boringssl.vcxproj]
  d:\projects\hfh\frontend-portal\node_modules\grpc\deps\grpc\third_party\boringssl\include\openssl\mem.h(88): warning C4030: first formal parameter list longer than the second list (compiling source file ..\deps\grpc\third_party\boringssl\crypto\asn1\a_d2i_fp.c) [D:\projects\HFH\frontend-portal\node_modules\grpc\build\boringssl.vcxproj]
  d:\projects\hfh\frontend-portal\node_modules\grpc\deps\grpc\third_party\boringssl\include\openssl\mem.h(105): warning C4030: first formal parameter list longer than the second list (compiling source file ..\deps\grpc\third_party\boringssl\crypto\asn1\a_d2i_fp.c) [D:\projects\HFH\frontend-portal\node_modules\grpc\build\boringssl.vcxproj]
  d:\projects\hfh\frontend-portal\node_modules\grpc\deps\grpc\third_party\boringssl\crypto\asn1\a_d2i_fp.c(76): warning C4013: 'OPENSSL_PUT_ERROR' undefined; assuming extern returning int [D:\projects\HFH\frontend-portal\node_modules\grpc\build\boringssl.vcxproj]
  d:\projects\hfh\frontend-portal\node_modules\grpc\deps\grpc\third_party\boringssl\include\openssl\base.h(143): warning C4005: 'OPENSSL_THREADS': macro redefinition (compiling source file ..\deps\grpc\third_party\boringssl\crypto\asn1\a_bitstr.c) [D:\projects\HFH\frontend-portal\node_modules\grpc\build\boringssl.vcxproj]
  d:\projects\hfh\frontend-portal\node_modules\grpc\deps\grpc\third_party\boringssl\include\openssl\base.h(147): warning C4005: 'OPENSSL_VERSION_NUMBER': macro redefinition (compiling source file ..\deps\grpc\third_party\boringssl\crypto\asn1\a_bitstr.c) [D:\projects\HFH\frontend-portal\node_modules\grpc\build\boringssl.vcxproj]
  d:\projects\hfh\frontend-portal\node_modules\grpc\deps\grpc\third_party\boringssl\include\openssl\base.h(182): warning C4005: 'OPENSSL_EXPORT': macro redefinition (compiling source file ..\deps\grpc\third_party\boringssl\crypto\asn1\a_bitstr.c) [D:\projects\HFH\frontend-portal\node_modules\grpc\build\boringssl.vcxproj]
  d:\projects\hfh\frontend-portal\node_modules\grpc\deps\grpc\third_party\boringssl\include\openssl\mem.h(79): warning C4030: first formal parameter list longer than the second list (compiling source file ..\deps\grpc\third_party\boringssl\crypto\asn1\a_bitstr.c) [D:\projects\HFH\frontend-portal\node_modules\grpc\build\boringssl.vcxproj]
  d:\projects\hfh\frontend-portal\node_modules\grpc\deps\grpc\third_party\boringssl\include\openssl\mem.h(83): warning C4030: first formal parameter list longer than the second list (compiling source file ..\deps\grpc\third_party\boringssl\crypto\asn1\a_bitstr.c) [D:\projects\HFH\frontend-portal\node_modules\grpc\build\boringssl.vcxproj]
  d:\projects\hfh\frontend-portal\node_modules\grpc\deps\grpc\third_party\boringssl\include\openssl\mem.h(88): warning C4030: first formal parameter list longer than the second list (compiling source file ..\deps\grpc\third_party\boringssl\crypto\asn1\a_bitstr.c) [D:\projects\HFH\frontend-portal\node_modules\grpc\build\boringssl.vcxproj]
  d:\projects\hfh\frontend-portal\node_modules\grpc\deps\grpc\third_party\boringssl\include`

**Comment by Jagadesh-Ram** [comment]
even am facing this issue any solutions now??

**Comment by Javelinl182** [comment]
Did installing 'windows-build-tools' work for some of you? Some say you have to try 'npm install -g windows-build-tools'

**Comment by Jagadesh-Ram** [comment]
@Javelinl182  no i don't see that fixing my issue...as a workaround i just copy the build files to make it work but that is not a valid solution since the npm modules of dependencies might update them after fixing some bugs, so till now i didn't find any proper fix!

**Comment by zenoscode** [comment]
yarn add tesseract
yarn add v1.22.10
[1/4] Resolving packages...
[2/4] Fetching packages...
info fsevents@2.3.1: The platform "win32" is incompatible with this module.
info "fsevents@2.3.1" is an optional dependency and failed compatibility check. Excluding it from installation.
[3/4] Linking dependencies...
[4/4] Building fresh packages...
[1/2] ⠈ nodemon
error D:\important\scripting\node_modules\tesseract: Command failed.
Exit code: 1
Command: node-gyp rebuild
Arguments:
Directory: D:\important\scripting\node_modules\tesseract
Output:
D:\important\scripting\node_modules\tesseract>if not defined npm_config_node_gyp (node "C:\Program Files\nodejs\node_modules\npm\bin\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild )  else (node "" rebuild )
gyp info it worked if it ends with ok
gyp info using node-gyp@3.8.0
gyp info using node@11.15.0 | win32 | x64
gyp info spawn C:\Users\panch\.windows-build-tools\python27\python.EXE
gyp info spawn args [ 'C:\\Users\\panch\\AppData\\Roaming\\nvm\\v11.15.0\\node_modules\\npm\\node_modules\\node-gyp\\gyp\\gyp_main.py',
gyp info spawn args   'binding.gyp',
gyp info spawn args   '-f',
gyp info spawn args   'msvs',
gyp info spawn args   '-G',
gyp info spawn args   'msvs_version=2015',
gyp info spawn args   '-I',
gyp info spawn args   'D:\\important\\scripting\\node_modules\\tesseract\\build\\config.gypi',
gyp info spawn args   '-I',
gyp info spawn args   'C:\\Users\\panch\\AppData\\Roaming\\nvm\\v11.15.0\\node_modules\\npm\\node_modules\\node-gyp\\addon.gypi',
gyp info spawn args   '-I',
gyp info spawn args   'C:\\Users\\panch\\.node-gyp\\11.15.0\\include\\node\\common.gypi',
gyp info spawn args   '-Dlibrary=shared_library',
gyp info spawn args   '-Dvisibility=default',
gyp info spawn args   '-Dnode_root_dir=C:\\Users\\panch\\.node-gyp\\11.15.0',
gyp info spawn args   '-Dnode_gyp_dir=C:\\Users\\panch\\AppData\\Roaming\\nvm\\v11.15.0\\node_modules\\npm\\node_modules\\node-gyp',
gyp info spawn args   '-Dnode_lib_file=C:\\Users\\panch\\.node-gyp\\11.15.0\\<(target_arch)\\node.lib',
gyp info spawn args   '-Dmodule_root_dir=D:\\important\\scripting\\node_modules\\tesseract',
gyp info spawn args   '-Dnode_engine=v8',
gyp info spawn args   '--depth=.',
gyp info spawn args   '--no-parallel',
gyp info spawn args   '--generator-output',
gyp info spawn args   'D:\\important\\scripting\\node_modules\\tesseract\\build',
gyp info spawn args   '-Goutput_dir=.' ]
gyp info spawn C:\Program Files (x86)\Microsoft Visual Studio\2017\BuildTools\MSBuild\15.0\Bin\MSBuild.exe
gyp info spawn args [ 'build/binding.sln',
gyp info spawn args   '/clp:Verbosity=minimal',
gyp info spawn args   '/nologo',
gyp info spawn args   '/p:Configuration=Release;Platform=x64' ]
Building the projects in this solution one at a time. To enable parallel build, please add the "/m" switch.
  tesseract_bindings.cc
  tesseract_baseapi.cc
  leptonica_pix.cc
  win_delay_load_hook.cc
d:\important\scripting\node_modules\tesseract\src\tesseract_baseapi.cc(7): warning C4005: 'BUILDING_NODE_EXTENSION': macro redefinition [D:\important\scripting\node_modules\tesseract\build\tesseract_bindings.vcxproj]
  d:\important\scripting\node_modules\tesseract\src\tesseract_baseapi.cc: note: see previous definition of 'BUILDING_NODE_EXTENSION'
d:\important\scripting\node_modules\tesseract\src\leptonica_pix.cc(7): warning C4005: 'BUILDING_NODE_EXTENSION': macro redefinition [D:\important\scripting\node_modules\tesseract\build\tesseract_bindings.vcxproj]
  d:\important\scripting\node_modules\tesseract\src\leptonica_pix.cc: note: see previous definition of 'BUILDING_NODE_EXTENSION'
d:\important\scripting\node_modules\tesseract\src\tesseract_bindings.cc(7): warning C4005: 'BUILDING_NODE_EXTENSION': macro redefinition [D:\important\scripting\node_modules\tesseract\build\tesseract_bindings.vcxproj]
  d:\important\scripting\node_modules\tesseract\src\tesseract_bindings.cc: note: see previous definition of 'BUILDING_NODE_EXTENSION'
d:\important\scripting\node_modules\tesseract\src\leptonica_pix.h(10): fatal error C1083: Cannot open include file: 'allheaders.h': No such file or directory (compiling source file ..\src\leptonica_pix.cc) [D:\important\scripting\node_modules\tesseract\build\tesseract_bindings.vcxproj]
d:\important\scripting\node_modules\tesseract\src\tesseract_baseapi.h(10): fatal error C1083: Cannot open include file: 'baseapi.h': No such file or directory (compiling source 
file ..\src\tesseract_bindings.cc) [D:\important\scripting\node_modules\tesseract\build\tesseract_bindings.vcxproj]
d:\important\scripting\node_modules\tesseract\src\tesseract_baseapi.h(10): fatal error C1083: Cannot open include file: 'baseapi.h': No such file or directory (compiling source 
file ..\src\tesseract_baseapi.cc) [D:\important\scripting\node_modules\tesseract\build\tesseract_bindings.vcxproj]
gyp ERR! build error
gyp ERR! stack Error: `C:\Program Files (x86)\Microsoft Visual Studio\2017\BuildTools\MSBuild\15.0\Bin\MSBuild.exe` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onExit (C:\Users\panch\AppData\Roaming\nvm\v11.15.0\node_modules\npm\node_modules\node-gyp\lib\build.js:262:23)
gyp ERR! stack     at ChildProcess.emit (events.js:193:13)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:255:12)
gyp ERR! System Windows_NT 10.0.18363
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd D:\important\scripting\node_modules\tesseract
gyp ERR! node -v v11.15.0
gyp ERR! node-gyp -v v3.8.0
gyp ERR! not ok


here it said cannot open include file allheaders.h now I just want to know that does installing windows-build-tools reconfigure for the header files because I had c++ running before. So how to configure it so that it points to this windows-build-tools libraries?

**Comment by jacobq** [comment]
> `yarn add tesseract`
> (snip)

```
d:\important\scripting\node_modules\tesseract\src\tesseract_bindings.cc(7): warning C4005: 'BUILDING_NODE_EXTENSION': macro redefinition [D:\important\scripting\node_modules\tesseract\build\tesseract_bindings.vcxproj]
d:\important\scripting\node_modules\tesseract\src\tesseract_bindings.cc: note: see previous definition of 'BUILDING_NODE_EXTENSION'
d:\important\scripting\node_modules\tesseract\src\leptonica_pix.h(10): fatal error C1083: Cannot open include file: 'allheaders.h': No such file or directory (compiling source file ..\src\leptonica_pix.cc) [D:\important\scripting\node_modules\tesseract\build\tesseract_bindings.vcxproj]
d:\important\scripting\node_modules\tesseract\src\tesseract_baseapi.h(10): fatal error C1083: Cannot open include file: 'baseapi.h': No such file or directory (compiling source
```
> (snip)
> here it said cannot open include file allheaders.h now I just want to know that does installing windows-build-tools reconfigure for the header files because I had c++ running before. So how to configure it so that it points to this windows-build-tools libraries?

@zenoscode No, I don't believe so. It just facilitates installation of Microsoft's build tools (and Python). IIUC the project being built still needs to take care of specifying its include paths, ensure that dependent libraries are installed, etc. (perhaps when you had it working previously you were using a different build tools version: 2015, 2017, 2019, ...). If you believe that what you're seeing is a problem caused by `windows-build-tools` please create a separate issue (the behavior you describe is not related to this issue).
