### ISSUE TITLE
install failed at postinstall script

### ISSUE THREAD

**Issue by AlanCutFlim** [felixrieseberg/windows-build-tools#218]
I've used the powershell with admin rights to install, but throw an error after downloaded  python-2.7.15.amd64.msi and  vs_BuildTools.exe. I have searched the whole Internet ,pls somebody help me : (
![image](https://user-images.githubusercontent.com/50612752/84982888-2e520b80-b16a-11ea-9315-16c99dd18bcc.png)

and here is error part of the npm log
![image](https://user-images.githubusercontent.com/50612752/84982915-3c079100-b16a-11ea-9134-857ffecaccda.png)

**Comment by SpiritLing** [comment]
I have a problem similar to yours, and I also seek solutions
```
$ set "PYTHON_MIRROR=http://npm.taobao.org/mirrors/python" && npm install --global --production windows-build-tools
npm WARN deprecated request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142

> windows-build-tools@5.2.2 postinstall D:\Program Data\nodejs\node_modules\windows-build-tools
> node ./dist/index.js



Downloading python-2.7.15.amd64.msi
[>                                            ] 0.0% (0 B/s)
Downloaded python-2.7.15.amd64.msi. Saved to C:\Users\spiri\.windows-build-tools\python-2.7.15.amd64.msi.
Downloading vs_BuildTools.exe
[>                                            ] 0.0% (0 B/s)
Downloaded vs_BuildTools.exe. Saved to C:\Users\spiri\.windows-build-tools\vs_BuildTools.exe.

Starting installation...
AssignProcessToJobObject: (87) The parameter is incorrect.
npm WARN rollback Rolling back windows-build-tools@5.2.2 failed (this is probably harmless): EBUSY: resource busy or locked, rmdir 'D:\Program Data\nodejs\node_modules\windows-build-tools'
npm ERR! code ELIFECYCLE
npm ERR! errno 2147483651
npm ERR! windows-build-tools@5.2.2 postinstall: `node ./dist/index.js`
npm ERR! Exit status 2147483651
npm ERR!
npm ERR! Failed at the windows-build-tools@5.2.2 postinstall script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\spiri\AppData\Roaming\npm-cache\_logs\2020-07-28T15_16_17_617Z-debug.log
```

**Comment by 363797271** [comment]
same too

**Comment by 363797271** [comment]
> I've used the powershell with admin rights to install, but throw an error after downloaded python-2.7.15.amd64.msi and vs_BuildTools.exe. I have searched the whole Internet ,pls somebody help me : (

Hello, I also encountered the same problem as you, and finally did not find the reason and solution.

Then I found other workarounds:

I found that when the command is executed here, ` vs_ BuildTools.exe `It has been downloaded to `C: [users \ [username] \. Windows build tools`.

Then I open it and perform the installation manually like this:


![img1](https://s1.ax1x.com/2020/09/07/wnFJ1g.png)

![img2](https://s1.ax1x.com/2020/09/07/wnFtXj.png)

(This tool is more than 1GB, which will take some time)

After installation, continue to install sharp in my project and succeed.

So I guess the failure in the command line may be due to the software being too large.

**Comment by Constaline** [comment]
So it worked for me is that i just update my npm to latest

**Comment by BoyZhouY** [comment]
> So it worked for me is that i just update my npm to latest

Thanks，Solved my problem。

**Comment by cybermanhao** [comment]
> (This tool is more than 1GB, which will take some time)
> 
> After installation, continue to install sharp in my project and succeed.
> 
> So I guess the failure in the command line may be due to the software being too large.

I have the amost same error message with main issue
>npm ERR! Starting installation...
npm ERR! AssignProcessToJobObject: (87) parameters is not correct。

I tried to re-install it in vs the same way as you did,but still cant solve my problem
my problem comes from npm install failed with **pngquant**,a piece of error message is below:
`npm ERR!   × Error: pngquant failed to build, make sure that libpng-dev is installed   `

node version 16.8.0
npm version 7.21.0

ways i tried(didnt solve the problem):
-re-install nvm and node to C
-use --vs2015
-delete the installers and run npm i -g windows-build-tools
-use --offline-installers="C:\Users\[myname]\.windows-build-tools" and error is below:
![image](https://user-images.githubusercontent.com/37235140/131686276-6a064ce9-9fa4-4941-9b00-f9edb05594bc.png)
> npm ERR! code 1
npm ERR! path C:\Users\32467\AppData\Roaming\nvm\v16.8.0\node_modules\windows-build-tools
npm ERR! command failed
npm ERR! command C:\WINDOWS\system32\cmd.exe /d /s /c node ./dist/index.js
npm ERR! Downloading installers failed. Error: TypeError: error is not a function
npm ERR!     at Object.copyInstallers (C:\Users\32467\AppData\Roaming\nvm\v16.8.0\node_modules\windows-build-tools\dist\offline.js:55:9)
npm ERR!     at async Object.aquireInstallers (C:\Users\32467\AppData\Roaming\nvm\v16.8.0\node_modules\windows-build-tools\dist\aquire-installers.js:23:13)
npm ERR! windows-build-tools will now exit.
>
