### ISSUE TITLE
Issue after running "npm i quick.db"

### ISSUE THREAD

**Issue by strikingwd** [felixrieseberg/windows-build-tools#233]
> better-sqlite3@7.1.2 install C:\Users\jordo\Desktop\QuackBot\node_modules\better-sqlite3
> prebuild-install || npm run build-release

prebuild-install WARN install No prebuilt binaries found (target=12.19.0 runtime=node arch=x64 libc= platform=win32)

> better-sqlite3@7.1.2 build-release C:\Users\jordo\Desktop\QuackBot\node_modules\better-sqlite3
> node-gyp rebuild --release

C:\Users\jordo\Desktop\QuackBot\node_modules\better-sqlite3>if not defined npm_config_node_gyp (node "C:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild --release )  else (node "C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\bin\node-gyp.js" rebuild --release )
Building the projects in this solution one at a time. To enable parallel build, please add the "/m" switch.
  extract_sqlite3
  sqlite3.c
  win_delay_load_hook.cc
  sqlite3.vcxproj -> C:\Users\jordo\Desktop\QuackBot\node_modules\better-sqlite3\build\Release\\sqlite3.lib
  better_sqlite3.cpp
  win_delay_load_hook.cc
C:\\Users\\jordo\\AppData\\Local\\node-gyp\\Cache\\12.19.0\\x64\\node.lib : fatal error LNK1127: library is corrupt [C:\Users\jordo\Desktop\QuackBot\node_modules\be
tter-sqlite3\build\better_sqlite3.vcxproj]
  test_extension.c
  win_delay_load_hook.cc
     Creating library C:\Users\jordo\Desktop\QuackBot\node_modules\better-sqlite3\build\Release\test_extension.lib and object C:\Users\jordo\Desktop\QuackBot\node_m
  odules\better-sqlite3\build\Release\test_extension.exp
  test_extension.vcxproj -> C:\Users\jordo\Desktop\QuackBot\node_modules\better-sqlite3\build\Release\\test_extension.node
gyp ERR! build error
gyp ERR! stack Error: `C:\Program Files (x86)\Microsoft Visual Studio\2017\BuildTools\MSBuild\15.0\Bin\MSBuild.exe` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onExit (C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\build.js:194:23)
gyp ERR! stack     at ChildProcess.emit (events.js:314:20)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:275:12)
gyp ERR! System Windows_NT 10.0.19042
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild" "--release"gyp ERR! cwd C:\Users\jordo\Desktop\QuackBot\node_modules\better-sqlite3
gyp ERR! node -v v12.19.0
gyp ERR! node-gyp -v v5.1.0
gyp ERR! not ok
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! better-sqlite3@7.1.2 build-release: `node-gyp rebuild --release`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the better-sqlite3@7.1.2 build-release script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
npm WARN Local package.json exists, but node_modules missing, did you mean to install?

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\jordo\AppData\Roaming\npm-cache\_logs\2020-12-31T07_15_25_249Z-debug.log
npm WARN quackbot@1.0.0 No description
npm WARN quackbot@1.0.0 No repository field.

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! better-sqlite3@7.1.2 install: `prebuild-install || npm run build-release`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the better-sqlite3@7.1.2 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\jordo\AppData\Roaming\npm-cache\_logs\2020-12-31T07_15_25_520Z-debug.log

**Comment by strikingwd** [comment]
I have did npm install -g windows-build-tools and then did npm i quick.db but didnt work

**Comment by jacobq** [comment]
Could you please explain why you believe this problem is related to `windows-build-tools`?
What did you find when searching the Internet for `node.lib : fatal error LNK1127: library is corrupt`?
You might want to have a look at https://github.com/JoshuaWise/better-sqlite3/issues/200#issuecomment-663930251
