### ISSUE TITLE
nodejs -> mariasql

### ISSUE THREAD

**Issue by 123ajit** [felixrieseberg/windows-build-tools#234]
$ node mariasql rebuild
module.js:515
    throw err;
    ^

Error: Cannot find module 'C:\Users\User\Desktop\packageforwarding\Backend\mariasql'
    at Function.Module._resolveFilename (module.js:513:15)
    at Function.Module._load (module.js:463:25)
    at Function.Module.runMain (module.js:653:10)
    at startup (bootstrap_node.js:187:16)
    at bootstrap_node.js:608:3

**Comment by jacobq** [comment]
How does this have anything at all to do with `windows-build-tools`?
