### ISSUE TITLE
Error in tailer.js

### ISSUE THREAD

**Issue by turnerhayes** [felixrieseberg/windows-build-tools#42]
```
C:\nvm\v0.10.27\node_modules\windows-build-tools\lib\install\tailer.js:9
f (typeof superClass !== "function" && superClass !== null) { throw new TypeEr
                                                                    ^
TypeError: Super expression must either be null or a function, not object
    at _inherits (C:\nvm\v0.10.27\node_modules\windows-build-tools\lib\install\t
ailer.js:9:113)
    at C:\nvm\v0.10.27\node_modules\windows-build-tools\lib\install\tailer.js:19
:3
    at Object.<anonymous> (C:\nvm\v0.10.27\node_modules\windows-build-tools\lib\
install\tailer.js:140:2)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (C:\nvm\v0.10.27\node_modules\windows-build-tools\lib\
install\index.js:11:14)
```

This is on Window 7 Enterprise SP1, node version v0.10.27, npm version 1.4.8

**Comment by A92hm** [comment]
I'm afraid we don't support older versions of node. If you look at package.json the required node version is `"node": ">=4.0.0"`
