### ISSUE TITLE
2.0 / 2017 Issue: Error in find-logfile

### ISSUE THREAD

**Issue by felixrieseberg** [felixrieseberg/windows-build-tools#89]
Just logging it here as an issue to fix:

```
> node ./lib/index.js

Downloading vs_BuildTools.exe
Downloading python-2.7.14.amd64.msi
[============================================>] 100.0% of 20.17 MB (6.72 MB/s)
Downloaded python-2.7.14.amd64.msi. Saved to C:\Users\Felix\.windows-build-tools\python-2.7.14.amd64.msi.
Starting installation...
Launched installers, now waiting for them to finish.
This will likely take some time - please be patient!
(node:11848) UnhandledPromiseRejectionWarning: TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string
    at assertPath (path.js:28:11)
    at Object.join (path.js:489:7)
    at C:\Users\Felix\AppData\Roaming\npm\node_modules\windows-build-tools\lib\utils\find-logfile.js:66:20
    at <anonymous>
(node:11848) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:11848) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
Waiting for installers... /
```

**Comment by felixrieseberg** [comment]
Now fixed!
