### ISSUE TITLE
windows-build-tools not installing Windows SDK 8.1?

### ISSUE THREAD

**Issue by chadly** [felixrieseberg/windows-build-tools#9]
From [the comment here](https://github.com/nodejs/node-gyp/pull/970#issuecomment-229361954), it seems like installing `windows-build-tools` should also install the Windows SDK 8.1.

From a win 10 machine, I ran (from administrator cmd prompt):

```
npm install windows-build-tools -g
npm install aglio
```

with this output:

```
> protagonist@1.4.1 install C:\dev\archon\webhooks\docs\node_modules\protagonist
> node-gyp rebuild


C:\dev\archon\webhooks\docs\node_modules\protagonist>if not defined npm_config_node_gyp (node "C:\Users\chad.lee\AppData\Roaming\npm\node_modules\npm\bin\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild )  else (node "" rebuild )
Warning: Missing input files:
C:\dev\archon\webhooks\docs\node_modules\protagonist\build\drafter\..\..\drafter\test\test-SchemaTest.cc
C:\dev\archon\webhooks\docs\node_modules\protagonist\build\drafter\..\..\drafter\test\test-RefractDataStructureTest.cc
C:\dev\archon\webhooks\docs\node_modules\protagonist\build\drafter\..\..\drafter\test\test-RefractSourceMapTest.cc
C:\dev\archon\webhooks\docs\node_modules\protagonist\build\drafter\..\..\drafter\test\test-RefractParseResultTest.cc
C:\dev\archon\webhooks\docs\node_modules\protagonist\build\drafter\..\..\drafter\test\test-SerializeResultTest.cc
C:\dev\archon\webhooks\docs\node_modules\protagonist\build\drafter\..\..\drafter\test\test-SerializeSourceMapTest.cc
C:\dev\archon\webhooks\docs\node_modules\protagonist\build\drafter\..\..\drafter\test\test-ElementFactoryTest.cc
C:\dev\archon\webhooks\docs\node_modules\protagonist\build\drafter\..\..\drafter\test\test-ApplyVisitorTest.cc
C:\dev\archon\webhooks\docs\node_modules\protagonist\build\drafter\..\..\drafter\test\test-CAPI.c
C:\dev\archon\webhooks\docs\node_modules\protagonist\build\drafter\..\..\drafter\test\test-ExtendElementTest.cc
C:\dev\archon\webhooks\docs\node_modules\protagonist\build\drafter\..\..\drafter\test\test-drafter.cc
C:\dev\archon\webhooks\docs\node_modules\protagonist\build\drafter\..\..\drafter\test\test-RenderTest.cc
C:\dev\archon\webhooks\docs\node_modules\protagonist\build\drafter\..\..\drafter\test\test-CircularReferenceTest.cc
C:\dev\archon\webhooks\docs\node_modules\protagonist\build\drafter\..\..\drafter\test\test-RefractAPITest.cc
C:\dev\archon\webhooks\docs\node_modules\protagonist\build\drafter\..\..\drafter\test\test-OneOfTest.cc
Building the projects in this solution one at a time. To enable parallel build, please add the "/m" switch.
C:\Program Files (x86)\MSBuild\Microsoft.Cpp\v4.0\V140\Platforms\x64\PlatformToolsets\v140\Toolset.targets(36,5): error
 MSB8036: The Windows SDK version 8.1 was not found. Install the required version of Windows SDK or change the SDK vers
ion in the project property pages or by right-clicking the solution and selecting "Retarget solution". [C:\dev\archon\w
ebhooks\docs\node_modules\protagonist\build\drafter\libdrafter.vcxproj]
C:\Program Files (x86)\MSBuild\Microsoft.Cpp\v4.0\V140\Platforms\x64\PlatformToolsets\v140\Toolset.targets(36,5): error
 MSB8036: The Windows SDK version 8.1 was not found. Install the required version of Windows SDK or change the SDK vers
ion in the project property pages or by right-clicking the solution and selecting "Retarget solution". [C:\dev\archon\w
ebhooks\docs\node_modules\protagonist\build\drafter\ext\snowcrash\libmarkdownparser.vcxproj]
C:\Program Files (x86)\MSBuild\Microsoft.Cpp\v4.0\V140\Platforms\x64\PlatformToolsets\v140\Toolset.targets(36,5): error
 MSB8036: The Windows SDK version 8.1 was not found. Install the required version of Windows SDK or change the SDK vers
ion in the project property pages or by right-clicking the solution and selecting "Retarget solution". [C:\dev\archon\w
ebhooks\docs\node_modules\protagonist\build\drafter\ext\snowcrash\libsnowcrash.vcxproj]
C:\Program Files (x86)\MSBuild\Microsoft.Cpp\v4.0\V140\Platforms\x64\PlatformToolsets\v140\Toolset.targets(36,5): error
 MSB8036: The Windows SDK version 8.1 was not found. Install the required version of Windows SDK or change the SDK vers
ion in the project property pages or by right-clicking the solution and selecting "Retarget solution". [C:\dev\archon\w
ebhooks\docs\node_modules\protagonist\build\drafter\libsos.vcxproj]
C:\Program Files (x86)\MSBuild\Microsoft.Cpp\v4.0\V140\Platforms\x64\PlatformToolsets\v140\Toolset.targets(36,5): error
 MSB8036: The Windows SDK version 8.1 was not found. Install the required version of Windows SDK or change the SDK vers
ion in the project property pages or by right-clicking the solution and selecting "Retarget solution". [C:\dev\archon\w
ebhooks\docs\node_modules\protagonist\build\drafter\ext\snowcrash\libsundown.vcxproj]
gyp ERR! build error
gyp ERR! stack Error: `C:\Program Files (x86)\MSBuild\14.0\bin\msbuild.exe` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onExit (C:\Users\chad.lee\AppData\Roaming\npm\node_modules\npm\node_modules\node-gyp\lib\build.js:276:23)
gyp ERR! stack     at emitTwo (events.js:106:13)
gyp ERR! stack     at ChildProcess.emit (events.js:191:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:204:12)
gyp ERR! System Windows_NT 10.0.10586
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\chad.lee\\AppData\\Roaming\\npm\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd C:\dev\archon\webhooks\docs\node_modules\protagonist
gyp ERR! node -v v6.2.2
gyp ERR! node-gyp -v v3.3.1
gyp ERR! not ok
npm WARN optional Skipping failed optional dependency /chokidar/fsevents:
npm WARN notsup Not compatible with your operating system or architecture: fsevents@1.0.12
npm ERR! Windows_NT 10.0.10586
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\chad.lee\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js" "install" "aglio" "--save-dev"
npm ERR! node v6.2.2
npm ERR! npm  v3.10.2
npm ERR! code ELIFECYCLE

npm ERR! protagonist@1.4.1 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the protagonist@1.4.1 install script 'node-gyp rebuild'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the protagonist package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs protagonist
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls protagonist
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     C:\dev\archon\webhooks\docs\npm-debug.log
```

Relevant line being `MSB8036: The Windows SDK version 8.1 was not found. Install the required version of Windows SDK...`

Is this something `windows-build-tools` should have installed and made available?

**Comment by A92hm** [comment]
@chadly Thank you for reporting this error. Unfortunately, I'm unable to reproduce the problem. Having said that, I cannot get the project to build by running the following commands on a clean install of Windows 10 on a VM. 
```bash
npm install windows-build-tools -g
npm install aglio
```
Nor by fallowing the instructions on [Windows installation for node-gyp](https://github.com/nodejs/node-gyp#installation)

Both those methods result in different build errors. Are you able to install `aglio` by following the Windows installation instruction for node-gyp?

**Comment by kneumei** [comment]
@chadly did you figure out a work around? I'm having the same problem

**Comment by ArtskydJ** [comment]
@kneumei @chadly are you guys able to install any of [these packages](https://github.com/Microsoft/nodejs-guidelines/blob/master/windows-environment.md#verify-everythings-working)?

**Comment by kneumei** [comment]
I did not try any of those, but I did try `nslog`. 

I switched to using the "normal" instructions for building with node-gyp instead of using `windows-build-tools` (installing vs 2015 + cpp tools, python) and now things are working for me. 

I'm not sure if this makes a difference or not, but I had installed vs 2015 + cpp tools already on my machine before installing `windows-build-tools` when I saw the error.

**Comment by ainthek** [comment]
having similar problem with npm install oracledb.

it complains with:
C:\Program Files (x86)\MSBuild\Microsoft.Cpp\v4.0\V140\Platforms\x64\PlatformToolsets\v140\Toolset.targets(36,5): error
 MSB8036: The Windows SDK version 8.1 was not found. Install the required version of Windows SDK or change the SDK vers
ion in the project property pages or by right-clicking the solution and selecting "Retarget solution". [C:\workspaces\i
nit\node_modules\oracledb\build\oracledb.vcxproj]

**Comment by spoggie** [comment]
I think the important command is: 
`npm config set msvs_version 2015`

**Comment by schungx** [comment]
Got the same error re no Windows 8.1 SDK.  Does it depend on C++ being installed with VS 2015 to get the Windows SDK?  Or maybe we should simply install the Windows 8.1 SDK?

**Comment by replete** [comment]
I'm getting [the same error](https://github.com/MayhemYDG/iltorb/issues/17) whilst trying to install the `brotli` npm package.

I'm using Windows 10 Enterprise latest and Visual Studio 2015.

**Comment by replete** [comment]
I believe I have found the cause of the problem:

1. I tried to manually install [this](http://download.microsoft.com/download/5/f/7/5f7acaeb-8363-451f-9425-68a90f98b238/visualcppbuildtools_full.exe) from the url `installerUrl` [here](https://github.com/felixrieseberg/windows-build-tools/blob/master/src/constants.js#L3).
2. I could not continue the installer without _uninstalling Visual Studio 2015_. 
![Error in setup](http://i.imgur.com/O4CETpB.jpg)

It seems likely that this package does not check that the installers exited cleanly, or rather, did not verify the installation was successful.

**Comment by MayhemYDG** [comment]
@replete 
Have you tried running the installed with these parameters? https://github.com/felixrieseberg/windows-build-tools/blob/042c1344762ffde1acac2ebbf4fd8a20cf8c4efa/ps1/launch-installer.ps1#L26-L28

**Comment by replete** [comment]
By coincidence, I had just done this.

The log file appear to confirm the issue:
`[2CFC:11A8][2016-10-10T17:00:10]i000: MUX:  Exit with 0x80044000 (Blocked)`

I will be updating the issue over at the windows-build-tools thread.

**Comment by replete** [comment]
I am going to run the Visual Studio setup, in hopes that I can add the 'Visual C++ Build Tools' - this seems to be the path I am supposed to take that is important enough to block setup.

**Comment by replete** [comment]
My problems disappeared after installing 'Visual C++' support in Visual Studio 2015 by re-running the installer.

To summarize:
* This package silently fails when installing the Visual C++ Build tools on systems with Visual Studio 2015 installed
* Workaround: Install Visual C++ projects support to Visual Studio 2015.

**Comment by wkentdag** [comment]
following up on @replete's tip (which worked for me - thanks!): 

on a fresh install of VS 2015, the application will prompt you to install the visual c++ build tools (which includes the windows 8.1 sdk) when you click "create new c++ project" - i stumbled over this at first

**Comment by MayhemYDG** [comment]
@felixrieseberg 
Do you think it's possible to fix this now that we know the root cause?

**Comment by AndrewPardoe** [comment]
VC++ Build Tools 2015 will fail install if VS 2015 is installed. This is a design issue, but also a technical issue. I completely endorse #1056 because the 2017 VS installer is designed to let you just lay down the tools you need. 

You should be able to install the C++ workload in VS 2015 *or* install the Win 8.1 SDK directly but LMK if you are blocked.

**Comment by Besatnias** [comment]
Just had this issue trying to build with `node-gyp`, It reads the binding, creates the build folder, and on configure I get this:

```
C:\Program Files (x86)\MSBuild\Microsoft.Cpp\v4.0\V140\Platforms\x64\PlatformTo
olsets\v140\Toolset.targets(36,5): error MSB8036: The Windows SDK version 8.1 w
as not found. Install the required version of Windows SDK or change the SDK ver
sion in the project property pages or by right-clicking the solution and select
ing "Retarget solution". [C:\Users\venta\projects\node\robot\build\binding.vcxp
roj]
gyp ERR! build error
gyp ERR! stack Error: `C:\Program Files (x86)\MSBuild\14.0\bin\msbuild.exe` fail
ed with exit code: 1
gyp ERR! stack     at ChildProcess.onExit (C:\Users\venta\AppData\Roaming\npm\no
de_modules\node-gyp\lib\build.js:276:23)
gyp ERR! stack     at emitTwo (events.js:106:13)
gyp ERR! stack     at ChildProcess.emit (events.js:191:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_proces
s.js:215:12)
gyp ERR! System Windows_NT 6.1.7601
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\venta\\AppDat
a\\Roaming\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "build"
gyp ERR! cwd C:\Users\venta\projects\node\robot
gyp ERR! node -v v7.4.0
gyp ERR! node-gyp -v v3.5.0
gyp ERR! not ok
```

I installed VS community today, so it should be the 2017 installer as you said and should not have had this issue.

**Comment by felixrieseberg** [comment]
@AndrewPardoe let me know if there are better standard parameters or different packages we should install - I'd personally love to make the 8.1 SDK available to people (because it still seems like the default for a few native Node modules out there).

**Comment by AndrewPardoe** [comment]
>> I installed VS community today, so it should be the 2017 installer as you said and should not have had this issue.

VS 2017 installer has Windows 8.1 SDK as an option in the "Desktop development with C++" workload. Are you installing from the command line or clicking through the UI?

**Comment by Besatnias** [comment]
Through the UI.

**Comment by AndrewPardoe** [comment]
So then I'm confused about the issue. 8.1 is an option in the UI. Does just selecting it in the UI not work for you?

**Comment by Besatnias** [comment]
Lol I installed only once. It took 3 days to download and install so I'm a
bit reluctant to uninstalling it, but if it's necessary I will. I did not
know that the recommended option did not include that.

**Comment by AndrewPardoe** [comment]
If you rerun setup it should give you an option to modify the install. You can include the SDK at that point. It should be much faster to download just the setup + the SDK.

3 days is really long. Bad internet where you live? You might consider using an ISO.

**Comment by Besatnias** [comment]
Yes, Venezuela. Also I had to reset the set up various times because it got
interrupted or stuck due to irregular connection. And I will try that.
Thanks for the advice.

**Comment by AndrewPardoe** [comment]
For reference, the VS 2017 installer has two major changes that impact this scenario:

1. VS no longer installs "everything". You need to pick your workload, and then the individual components if a workload doesn't match your scenario exactly. It appears that node folks need to pick the Windows 8.1 SDK.
2. The good side is that VS no longer downloads everything. You download a (relatively) small installer, and then individual packages are downloaded. This should help in low-bandwidth scenarios. 
3. As point 2 implies, modifying your installation doesn't require downloading anything more than the installer (if it's not still on your machine) and the modified components. 

More about the VS 2017 installer can be found on the Visual Studio blog, e.g., https://blogs.msdn.microsoft.com/visualstudio/2016/06/17/redesigning-visual-studio-installation/

Also, if you're in a situation where you can download everything to create an offline install,  you can do that with VS 2017: https://docs.microsoft.com/en-us/visualstudio/install/create-an-offline-installation-of-visual-studio

**Comment by SCLeoX** [comment]
I really think some windows updates break it. I was able to compile native modules like a week ago, but now it tells me it cannot find Windows SDK 8.1.

There is a really high chance it is actually caused by windows' updates because since windows 10, windows updates regularly breaks stuff (network, font render, etc...). Surely Microsoft developers did not even lint nor try their code before uploading to windows update server.

Again, I am sure, the compile thing was working a week ago but now it is not. The only thing I can think of that changed my computer is windows update.

**Comment by izeta** [comment]
I installed the Visual C++ tools and 8.1 SDK from within Visual Studio when trying to create a new C++ project. After that it worked. This didn't need to uninstall Visual Studio first.
http://stackoverflow.com/a/38387213/678586

**Comment by vmatt** [comment]
My solution
1. Clone the problematic module from github.
2. Open the build folder
3. Open the *.sln file.
4. The Visual Studio will open, and you can select to install the 8.1 SDK.:
![image](https://cloud.githubusercontent.com/assets/3168272/24703804/2992253a-1a05-11e7-8af2-5648d5bf6e1a.png)

**Comment by tobeorla** [comment]
@vmatt it's more easier to click on New Project and select c++ one. It will display the download option too.

**Comment by jasonLiu001** [comment]
Thank you for all of you. I solved my problem through modified visual studio 2015 installation.
